/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { AddTrackingEventsEvents } from './addTrackingEventsEvents';

export class AddTrackingEventsReferences {
    'referenceType'?: string;
    'referenceValue'?: string;
    'events'?: Array<AddTrackingEventsEvents>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "referenceType",
            "baseName": "referenceType",
            "type": "string"
        },
        {
            "name": "referenceValue",
            "baseName": "referenceValue",
            "type": "string"
        },
        {
            "name": "events",
            "baseName": "events",
            "type": "Array<AddTrackingEventsEvents>"
        }    ];

    static getAttributeTypeMap() {
        return AddTrackingEventsReferences.attributeTypeMap;
    }
}

