/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class CarrierFacilityResponseFacilityTimings {
    'closesAt'?: string;
    'opensAt'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "closesAt",
            "baseName": "closesAt",
            "type": "string"
        },
        {
            "name": "opensAt",
            "baseName": "opensAt",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CarrierFacilityResponseFacilityTimings.attributeTypeMap;
    }
}

