/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { Address } from './address';
import { CarrierFacilityResponseCarrierFacilityOptions } from './carrierFacilityResponseCarrierFacilityOptions';
import { CarrierFacilityResponseCarrierFacilitySuggestions } from './carrierFacilityResponseCarrierFacilitySuggestions';

export class CarrierFacilityResponse {
    'address'?: Address;
    'carrier'?: string;
    'carrierFacilityOptions'?: Array<CarrierFacilityResponseCarrierFacilityOptions>;
    'carrierFacilitySuggestions'?: Array<CarrierFacilityResponseCarrierFacilitySuggestions>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "Address"
        },
        {
            "name": "carrier",
            "baseName": "carrier",
            "type": "string"
        },
        {
            "name": "carrierFacilityOptions",
            "baseName": "carrierFacilityOptions",
            "type": "Array<CarrierFacilityResponseCarrierFacilityOptions>"
        },
        {
            "name": "carrierFacilitySuggestions",
            "baseName": "carrierFacilitySuggestions",
            "type": "Array<CarrierFacilityResponseCarrierFacilitySuggestions>"
        }    ];

    static getAttributeTypeMap() {
        return CarrierFacilityResponse.attributeTypeMap;
    }
}

