/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { CarrierFacilityRequestAddress } from './carrierFacilityRequestAddress';
import { CarrierFacilityResponseCarrierFacilityOptions } from './carrierFacilityResponseCarrierFacilityOptions';

export class CarrierFacilityRequest {
    'address'?: CarrierFacilityRequestAddress;
    'carrier'?: string;
    'carrierFacilityOptions'?: Array<CarrierFacilityResponseCarrierFacilityOptions>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "CarrierFacilityRequestAddress"
        },
        {
            "name": "carrier",
            "baseName": "carrier",
            "type": "string"
        },
        {
            "name": "carrierFacilityOptions",
            "baseName": "carrierFacilityOptions",
            "type": "Array<CarrierFacilityResponseCarrierFacilityOptions>"
        }    ];

    static getAttributeTypeMap() {
        return CarrierFacilityRequest.attributeTypeMap;
    }
}

