/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class CarrierPayment {
    'accountNumber'?: string;
    'countryCode'?: string;
    'party': CarrierPayment.PartyEnum;
    'postalCode'?: string;
    'typeOfCharge': CarrierPayment.TypeOfChargeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accountNumber",
            "baseName": "accountNumber",
            "type": "string"
        },
        {
            "name": "countryCode",
            "baseName": "countryCode",
            "type": "string"
        },
        {
            "name": "party",
            "baseName": "party",
            "type": "CarrierPayment.PartyEnum"
        },
        {
            "name": "postalCode",
            "baseName": "postalCode",
            "type": "string"
        },
        {
            "name": "typeOfCharge",
            "baseName": "typeOfCharge",
            "type": "CarrierPayment.TypeOfChargeEnum"
        }    ];

    static getAttributeTypeMap() {
        return CarrierPayment.attributeTypeMap;
    }
}

export namespace CarrierPayment {
    export enum PartyEnum {
        RECEIVER = <any> 'BILL_RECEIVER',
        SENDER = <any> 'BILL_SENDER',
        THIRDPARTY = <any> 'BILL_THIRD_PARTY',
        RECEIVERCONTRACT = <any> 'BILL_RECEIVER_CONTRACT'
    }
    export enum TypeOfChargeEnum {
        TRANSPORTATIONCHARGES = <any> 'TRANSPORTATION_CHARGES',
        DUTIESANDTAXES = <any> 'DUTIES_AND_TAXES',
        ALLCHARGES = <any> 'ALL_CHARGES'
    }
}
