/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { CarrierFacilityResponseFacilityTimings } from './carrierFacilityResponseFacilityTimings';

export class CarrierFacilityResponseFacilityHours {
    'day'?: string;
    'facilityTimings'?: Array<CarrierFacilityResponseFacilityTimings>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "day",
            "baseName": "day",
            "type": "string"
        },
        {
            "name": "facilityTimings",
            "baseName": "facilityTimings",
            "type": "Array<CarrierFacilityResponseFacilityTimings>"
        }    ];

    static getAttributeTypeMap() {
        return CarrierFacilityResponseFacilityHours.attributeTypeMap;
    }
}

