/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class CrossBorderQuotesRequestDescriptions {
    'locale'?: string;
    'name'?: string;
    'parentsNames'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "locale",
            "baseName": "locale",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "parentsNames",
            "baseName": "parentsNames",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return CrossBorderQuotesRequestDescriptions.attributeTypeMap;
    }
}

