/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class CrossBorderQuotesRequestPricingCodPrice {
    'price'?: number;
    'cod'?: string;
    'includesDuty'?: boolean;
    'includesTaxes'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "price",
            "baseName": "price",
            "type": "number"
        },
        {
            "name": "cod",
            "baseName": "cod",
            "type": "string"
        },
        {
            "name": "includesDuty",
            "baseName": "includesDuty",
            "type": "boolean"
        },
        {
            "name": "includesTaxes",
            "baseName": "includesTaxes",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return CrossBorderQuotesRequestPricingCodPrice.attributeTypeMap;
    }
}

