/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { CrossBorderQuotesErrorsQuote } from './crossBorderQuotesErrorsQuote';

export class CrossBorderQuotesErrors {
    'quote'?: Array<CrossBorderQuotesErrorsQuote>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "quote",
            "baseName": "quote",
            "type": "Array<CrossBorderQuotesErrorsQuote>"
        }    ];

    static getAttributeTypeMap() {
        return CrossBorderQuotesErrors.attributeTypeMap;
    }
}

