/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { CrossBorderQuotesResponseUnitRatesDeliveryCommitment } from './crossBorderQuotesResponseUnitRatesDeliveryCommitment';

export class CrossBorderQuotesResponseUnitRates {
    'unitPrice'?: number;
    'totalTaxAmount'?: number;
    'totalDutyAmount'?: number;
    'serviceId'?: string;
    'baseCharge'?: number;
    'deliveryCommitment'?: CrossBorderQuotesResponseUnitRatesDeliveryCommitment;
    'totalCarrierCharge'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "unitPrice",
            "baseName": "unitPrice",
            "type": "number"
        },
        {
            "name": "totalTaxAmount",
            "baseName": "totalTaxAmount",
            "type": "number"
        },
        {
            "name": "totalDutyAmount",
            "baseName": "totalDutyAmount",
            "type": "number"
        },
        {
            "name": "serviceId",
            "baseName": "serviceId",
            "type": "string"
        },
        {
            "name": "baseCharge",
            "baseName": "baseCharge",
            "type": "number"
        },
        {
            "name": "deliveryCommitment",
            "baseName": "deliveryCommitment",
            "type": "CrossBorderQuotesResponseUnitRatesDeliveryCommitment"
        },
        {
            "name": "totalCarrierCharge",
            "baseName": "totalCarrierCharge",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CrossBorderQuotesResponseUnitRates.attributeTypeMap;
    }
}

