/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { Address } from './address';
import { ParcelWeight } from './parcelWeight';

export class CustomsItem {
    'description': string;
    'hSTariffCode'?: string;
    'netCostMethod'?: CustomsItem.NetCostMethodEnum;
    'originCountryCode': string;
    'originStateProvince'?: string;
    'preferenceCriterion'?: CustomsItem.PreferenceCriterionEnum;
    'producerAddress'?: Address;
    'producerDetermination'?: CustomsItem.ProducerDeterminationEnum;
    'producerId'?: string;
    'quantity': number;
    'quantityUOM'?: string;
    'unitPrice': number;
    'unitWeight': ParcelWeight;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "hSTariffCode",
            "baseName": "hSTariffCode",
            "type": "string"
        },
        {
            "name": "netCostMethod",
            "baseName": "netCostMethod",
            "type": "CustomsItem.NetCostMethodEnum"
        },
        {
            "name": "originCountryCode",
            "baseName": "originCountryCode",
            "type": "string"
        },
        {
            "name": "originStateProvince",
            "baseName": "originStateProvince",
            "type": "string"
        },
        {
            "name": "preferenceCriterion",
            "baseName": "preferenceCriterion",
            "type": "CustomsItem.PreferenceCriterionEnum"
        },
        {
            "name": "producerAddress",
            "baseName": "producerAddress",
            "type": "Address"
        },
        {
            "name": "producerDetermination",
            "baseName": "producerDetermination",
            "type": "CustomsItem.ProducerDeterminationEnum"
        },
        {
            "name": "producerId",
            "baseName": "producerId",
            "type": "string"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        },
        {
            "name": "quantityUOM",
            "baseName": "quantityUOM",
            "type": "string"
        },
        {
            "name": "unitPrice",
            "baseName": "unitPrice",
            "type": "number"
        },
        {
            "name": "unitWeight",
            "baseName": "unitWeight",
            "type": "ParcelWeight"
        }    ];

    static getAttributeTypeMap() {
        return CustomsItem.attributeTypeMap;
    }
}

export namespace CustomsItem {
    export enum NetCostMethodEnum {
        NONETCOST = <any> 'NO_NET_COST',
        NETCOST = <any> 'NET_COST'
    }
    export enum PreferenceCriterionEnum {
        A = <any> 'A',
        B = <any> 'B',
        C = <any> 'C',
        D = <any> 'D',
        E = <any> 'E',
        F = <any> 'F'
    }
    export enum ProducerDeterminationEnum {
        NO1 = <any> 'NO_1',
        NO2 = <any> 'NO_2',
        NO3 = <any> 'NO_3',
        PDYES = <any> 'PD_YES'
    }
}
