/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class ParcelProtectionPolicyResponseSort {
    'direction'?: string;
    'property'?: string;
    'ignoreCase'?: boolean;
    'nullHandling'?: string;
    'descending'?: boolean;
    'ascending'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "direction",
            "baseName": "direction",
            "type": "string"
        },
        {
            "name": "property",
            "baseName": "property",
            "type": "string"
        },
        {
            "name": "ignoreCase",
            "baseName": "ignoreCase",
            "type": "boolean"
        },
        {
            "name": "nullHandling",
            "baseName": "nullHandling",
            "type": "string"
        },
        {
            "name": "descending",
            "baseName": "descending",
            "type": "boolean"
        },
        {
            "name": "ascending",
            "baseName": "ascending",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return ParcelProtectionPolicyResponseSort.attributeTypeMap;
    }
}

