/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class ParcelProtectionQuoteResponseParcelProtectionFeesBreakup {
    'basePremium': number;
    'technologyFee': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "basePremium",
            "baseName": "basePremium",
            "type": "number"
        },
        {
            "name": "technologyFee",
            "baseName": "technologyFee",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ParcelProtectionQuoteResponseParcelProtectionFeesBreakup.attributeTypeMap;
    }
}

