/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { ParcelProtectionPolicyResponseContent } from './parcelProtectionPolicyResponseContent';
import { ParcelProtectionPolicyResponseSort } from './parcelProtectionPolicyResponseSort';

export class ParcelProtectionPolicyResponse {
    'content'?: Array<ParcelProtectionPolicyResponseContent>;
    'last'?: boolean;
    'totalElements'?: number;
    'totalPages'?: number;
    'first'?: boolean;
    'numberOfElements'?: number;
    'sort'?: Array<ParcelProtectionPolicyResponseSort>;
    'size'?: number;
    'number'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "content",
            "baseName": "content",
            "type": "Array<ParcelProtectionPolicyResponseContent>"
        },
        {
            "name": "last",
            "baseName": "last",
            "type": "boolean"
        },
        {
            "name": "totalElements",
            "baseName": "totalElements",
            "type": "number"
        },
        {
            "name": "totalPages",
            "baseName": "totalPages",
            "type": "number"
        },
        {
            "name": "first",
            "baseName": "first",
            "type": "boolean"
        },
        {
            "name": "numberOfElements",
            "baseName": "numberOfElements",
            "type": "number"
        },
        {
            "name": "sort",
            "baseName": "sort",
            "type": "Array<ParcelProtectionPolicyResponseSort>"
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "number"
        },
        {
            "name": "number",
            "baseName": "number",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ParcelProtectionPolicyResponse.attributeTypeMap;
    }
}

