/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { ParcelProtectionQuoteRequestShipmentInfoConsigneeInfo } from './parcelProtectionQuoteRequestShipmentInfoConsigneeInfo';
import { ParcelProtectionQuoteRequestShipmentInfoParcelInfo } from './parcelProtectionQuoteRequestShipmentInfoParcelInfo';
import { ParcelProtectionQuoteRequestShipmentInfoShipperInfo } from './parcelProtectionQuoteRequestShipmentInfoShipperInfo';

export class ParcelProtectionQuoteRequestShipmentInfo {
    'carrier': string;
    'serviceId': string;
    'insuranceCoverageValue': number;
    'insuranceCoverageValueCurrency': string;
    'parcelInfo': ParcelProtectionQuoteRequestShipmentInfoParcelInfo;
    'shipperInfo': ParcelProtectionQuoteRequestShipmentInfoShipperInfo;
    'consigneeInfo': ParcelProtectionQuoteRequestShipmentInfoConsigneeInfo;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "carrier",
            "baseName": "carrier",
            "type": "string"
        },
        {
            "name": "serviceId",
            "baseName": "serviceId",
            "type": "string"
        },
        {
            "name": "insuranceCoverageValue",
            "baseName": "insuranceCoverageValue",
            "type": "number"
        },
        {
            "name": "insuranceCoverageValueCurrency",
            "baseName": "insuranceCoverageValueCurrency",
            "type": "string"
        },
        {
            "name": "parcelInfo",
            "baseName": "parcelInfo",
            "type": "ParcelProtectionQuoteRequestShipmentInfoParcelInfo"
        },
        {
            "name": "shipperInfo",
            "baseName": "shipperInfo",
            "type": "ParcelProtectionQuoteRequestShipmentInfoShipperInfo"
        },
        {
            "name": "consigneeInfo",
            "baseName": "consigneeInfo",
            "type": "ParcelProtectionQuoteRequestShipmentInfoConsigneeInfo"
        }    ];

    static getAttributeTypeMap() {
        return ParcelProtectionQuoteRequestShipmentInfo.attributeTypeMap;
    }
}

