/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { ParcelProtectionQuoteRequestShipmentInfoParcelInfoCommodityList } from './parcelProtectionQuoteRequestShipmentInfoParcelInfoCommodityList';

export class ParcelProtectionQuoteRequestShipmentInfoParcelInfo {
    'commodityList': Array<ParcelProtectionQuoteRequestShipmentInfoParcelInfoCommodityList>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "commodityList",
            "baseName": "commodityList",
            "type": "Array<ParcelProtectionQuoteRequestShipmentInfoParcelInfoCommodityList>"
        }    ];

    static getAttributeTypeMap() {
        return ParcelProtectionQuoteRequestShipmentInfoParcelInfo.attributeTypeMap;
    }
}

