/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { ParcelProtectionQuoteResponseParcelProtectionFeesBreakup } from './parcelProtectionQuoteResponseParcelProtectionFeesBreakup';

export class ParcelProtectionQuoteResponse {
    'parcelProtectionFees': number;
    'parcelProtectionFeesCurrencyCode': string;
    'parcelProtectionFeesBreakup': ParcelProtectionQuoteResponseParcelProtectionFeesBreakup;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "parcelProtectionFees",
            "baseName": "parcelProtectionFees",
            "type": "number"
        },
        {
            "name": "parcelProtectionFeesCurrencyCode",
            "baseName": "parcelProtectionFeesCurrencyCode",
            "type": "string"
        },
        {
            "name": "parcelProtectionFeesBreakup",
            "baseName": "parcelProtectionFeesBreakup",
            "type": "ParcelProtectionQuoteResponseParcelProtectionFeesBreakup"
        }    ];

    static getAttributeTypeMap() {
        return ParcelProtectionQuoteResponse.attributeTypeMap;
    }
}

