/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class ParcelProtectionQuoteRequestShipmentInfoParcelInfoCommodityList {
    'categoryPath': string;
    'itemCode': string;
    'name': string;
    'url': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "categoryPath",
            "baseName": "categoryPath",
            "type": "string"
        },
        {
            "name": "itemCode",
            "baseName": "itemCode",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ParcelProtectionQuoteRequestShipmentInfoParcelInfoCommodityList.attributeTypeMap;
    }
}

