/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { ParcelProtectionCreateRequestShipmentInfo } from './parcelProtectionCreateRequestShipmentInfo';

export class ParcelProtectionCreateRequest {
    'parcelProtectionAccountID'?: string;
    'parcelProtectionProgramID'?: string;
    'shipmentInfo'?: ParcelProtectionCreateRequestShipmentInfo;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "parcelProtectionAccountID",
            "baseName": "parcelProtectionAccountID",
            "type": "string"
        },
        {
            "name": "parcelProtectionProgramID",
            "baseName": "parcelProtectionProgramID",
            "type": "string"
        },
        {
            "name": "shipmentInfo",
            "baseName": "shipmentInfo",
            "type": "ParcelProtectionCreateRequestShipmentInfo"
        }    ];

    static getAttributeTypeMap() {
        return ParcelProtectionCreateRequest.attributeTypeMap;
    }
}

