/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class RadioNuclideDetail {
    'chemicalForm'?: string;
    'expectedPackageReportableQuantity'?: boolean;
    'physicalForm'?: string;
    'radioNuclide'?: string;
    'radioNuclideActivityUOM'?: string;
    'radioNuclideActivityValue'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "chemicalForm",
            "baseName": "chemicalForm",
            "type": "string"
        },
        {
            "name": "expectedPackageReportableQuantity",
            "baseName": "expectedPackageReportableQuantity",
            "type": "boolean"
        },
        {
            "name": "physicalForm",
            "baseName": "physicalForm",
            "type": "string"
        },
        {
            "name": "radioNuclide",
            "baseName": "radioNuclide",
            "type": "string"
        },
        {
            "name": "radioNuclideActivityUOM",
            "baseName": "radioNuclideActivityUOM",
            "type": "string"
        },
        {
            "name": "radioNuclideActivityValue",
            "baseName": "radioNuclideActivityValue",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return RadioNuclideDetail.attributeTypeMap;
    }
}

