/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { PrerequisiteRules } from './prerequisiteRules';
import { ServicesParameterRule } from './servicesParameterRule';
import { SpecialServiceCodes } from './specialServiceCodes';

export class SpecialServicesRule {
    'specialServiceId'?: SpecialServiceCodes;
    'brandedName'?: string;
    'categoryId'?: string;
    'categoryName'?: string;
    'trackable'?: boolean;
    'inputParameterRules'?: Array<ServicesParameterRule>;
    'prerequisiteRules'?: Array<PrerequisiteRules>;
    'incompatibleSpecialServices'?: SpecialServiceCodes;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "specialServiceId",
            "baseName": "specialServiceId",
            "type": "SpecialServiceCodes"
        },
        {
            "name": "brandedName",
            "baseName": "brandedName",
            "type": "string"
        },
        {
            "name": "categoryId",
            "baseName": "categoryId",
            "type": "string"
        },
        {
            "name": "categoryName",
            "baseName": "categoryName",
            "type": "string"
        },
        {
            "name": "trackable",
            "baseName": "trackable",
            "type": "boolean"
        },
        {
            "name": "inputParameterRules",
            "baseName": "inputParameterRules",
            "type": "Array<ServicesParameterRule>"
        },
        {
            "name": "prerequisiteRules",
            "baseName": "prerequisiteRules",
            "type": "Array<PrerequisiteRules>"
        },
        {
            "name": "incompatibleSpecialServices",
            "baseName": "incompatibleSpecialServices",
            "type": "SpecialServiceCodes"
        }    ];

    static getAttributeTypeMap() {
        return SpecialServicesRule.attributeTypeMap;
    }
}

