/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

/**
* * Ins - Insured Mail.  * RR - Return receipt.  * Sig - Item is trackable if special service is requested. * ADSIG - Adult signature required. * Cert - Certified mail. * DelCon - Delivery confirmation. * ERR - Electronic return receipt. * RRm - Return receipt for merchandise. * Reg - Registered mail. * RegIns - Registered mail with insurance. * SH - Special handling - fragile. * CertRD - Certified mail with restricted delivery. * COD - Collect on delivery. * CODRD - Collect on delivery with restricted delivery. * InsRD - Insurance with restricted delivery. * RegRD - Registered mail with restricted delivery. * RegCOD - Registered mail with COD. * SigRD - Signature required with restricted delivery. * ADSIGRD - Adult signature required with restricted delivery. * RegInsRD - Registered mail with insurance and restricted delivery. * CERTAD - Certified mail with adult signature. * CERTADRD - Certified mail with adult signature and restricted delivery. * hazmat - Hazardous materials. * liveanimal - Live animal surcharge. * liveanimal_poultry - Live Animal-Day Old Poultry Surcharge * holiday - Holiday Delivery- For Priority Mail Express Service Only * sunday - Sunday delivery. * sunday_holiday - Sunday and holiday delivery. * PO_to_Addressee - PO to addressee * noWeekend - Do not deliver on weekend * TenThirty - Delivery by 10:30 AM * PMOD_OPTIONS - PMOD options * NOTIFICATIONS - Notifications. 
*/
export enum SpecialServiceCodes {
    ADSIG = <any> 'ADSIG',
    ADSIGRD = <any> 'ADSIGRD',
    Cert = <any> 'Cert',
    CERTAD = <any> 'CERTAD',
    CERTADRD = <any> 'CERTADRD',
    CertRD = <any> 'CertRD',
    COD = <any> 'COD',
    CODRD = <any> 'CODRD',
    DelCon = <any> 'DelCon',
    ERR = <any> 'ERR',
    Hazmat = <any> 'hazmat',
    Holiday = <any> 'holiday',
    InsRD = <any> 'InsRD',
    Liveanimal = <any> 'liveanimal',
    LiveanimalPoultry = <any> 'liveanimal - poultry',
    PMODOPTIONS = <any> 'PMOD_OPTIONS',
    Reg = <any> 'Reg',
    RegCOD = <any> 'RegCOD',
    RegIns = <any> 'RegIns',
    RegInsRD = <any> 'RegInsRD',
    RegRD = <any> 'RegRD',
    RR = <any> 'RR',
    RRM = <any> 'RRM',
    SH = <any> 'SH',
    SIG = <any> 'SIG',
    SigRD = <any> 'SigRD',
    Sunday = <any> 'sunday',
    SundayHoliday = <any> 'sunday - holiday',
    NOTIFICATIONS = <any> 'NOTIFICATIONS',
    PBXPS = <any> 'PBXPS',
    PBXUS = <any> 'PBXUS',
    PBXPE = <any> 'PBXPE',
    ANCILLARYENDORSEMENT = <any> 'ANCILLARY_ENDORSEMENT',
    ADDHDL = <any> 'ADD_HDL',
    ALCOHOL = <any> 'ALCOHOL',
    CARRIERLEAVEIFNORES = <any> 'CARRIER_LEAVE_IF_NO_RES',
    DIRECTSIG = <any> 'DIRECT_SIG',
    APPOINTMENT = <any> 'APPOINTMENT',
    DATE = <any> 'DATE',
    EVENING = <any> 'EVENING',
    GCOD = <any> 'GCOD',
    PAL = <any> 'PAL',
    PALPLUS = <any> 'PAL_PLUS',
    SATDELIVERY = <any> 'SAT_DELIVERY',
    SATPICKUP = <any> 'SAT_PICKUP',
    HOLD = <any> 'HOLD',
    NOSIG = <any> 'NO_SIG',
    PRL = <any> 'PRL',
    ADULTSIG = <any> 'ADULT_SIG',
    CARBON = <any> 'CARBON',
    CODCASHIER = <any> 'COD_CASHIER',
    CODCHECK = <any> 'COD_CHECK',
    DELCON = <any> 'DEL_CON',
    DIRECT = <any> 'DIRECT',
    DRYICE = <any> 'DRY_ICE',
    INS = <any> 'INS',
    SHPRELEASE = <any> 'SHP_RELEASE',
    VERBAL = <any> 'VERBAL'
}
