/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

/**
* * TRACKABLE - Item is trackable by default. * NON_TRACKABLE - Item is not trackable. * REQUIRES_TRACKABLE_SPECIAL_SERVICE - Item is trackable if special service is requested. 
*/
export enum Trackable {
    TRACKABLE = <any> 'TRACKABLE',
    NONTRACKABLE = <any> 'NON_TRACKABLE',
    REQUIRESTRACKABLESPECIALSERVICE = <any> 'REQUIRES_TRACKABLE_SPECIAL_SERVICE'
}
