/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class TrackingResponseScanDetailsList {
    'eventDate'?: string;
    'eventTime'?: string;
    'eventCity'?: string;
    'eventStateOrProvince'?: string;
    'postalCode'?: number;
    'country'?: string;
    'scanType'?: string;
    'scanDescription'?: string;
    'packageStatus'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "eventDate",
            "baseName": "eventDate",
            "type": "string"
        },
        {
            "name": "eventTime",
            "baseName": "eventTime",
            "type": "string"
        },
        {
            "name": "eventCity",
            "baseName": "eventCity",
            "type": "string"
        },
        {
            "name": "eventStateOrProvince",
            "baseName": "eventStateOrProvince",
            "type": "string"
        },
        {
            "name": "postalCode",
            "baseName": "postalCode",
            "type": "number"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string"
        },
        {
            "name": "scanType",
            "baseName": "scanType",
            "type": "string"
        },
        {
            "name": "scanDescription",
            "baseName": "scanDescription",
            "type": "string"
        },
        {
            "name": "packageStatus",
            "baseName": "packageStatus",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return TrackingResponseScanDetailsList.attributeTypeMap;
    }
}

