/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { TrackingAddress } from './trackingAddress';
import { TrackingResponseScanDetailsList } from './trackingResponseScanDetailsList';

export class TrackingResponse {
    'packageCount'?: number;
    'carrier'?: string;
    'trackingNumber'?: string;
    'referenceNumber'?: string;
    'status'?: TrackingResponse.StatusEnum;
    'updatedDate'?: string;
    'updatedTime'?: string;
    'shipDate'?: string;
    'estimatedDeliveryDate'?: string;
    'estimatedDeliveryTime'?: string;
    'deliveryDate'?: string;
    'deliveryTime'?: string;
    'deliveryLocation'?: string;
    'deliveryLocationDescription'?: string;
    'signedBy'?: string;
    'weight'?: number;
    'weightOUM'?: TrackingResponse.WeightOUMEnum;
    'reattemptDate'?: string;
    'reattemptTime'?: string;
    'destinationAddress'?: TrackingAddress;
    'senderAddress'?: TrackingAddress;
    'scanDetailsList'?: Array<TrackingResponseScanDetailsList>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "packageCount",
            "baseName": "packageCount",
            "type": "number"
        },
        {
            "name": "carrier",
            "baseName": "carrier",
            "type": "string"
        },
        {
            "name": "trackingNumber",
            "baseName": "trackingNumber",
            "type": "string"
        },
        {
            "name": "referenceNumber",
            "baseName": "referenceNumber",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "TrackingResponse.StatusEnum"
        },
        {
            "name": "updatedDate",
            "baseName": "updatedDate",
            "type": "string"
        },
        {
            "name": "updatedTime",
            "baseName": "updatedTime",
            "type": "string"
        },
        {
            "name": "shipDate",
            "baseName": "shipDate",
            "type": "string"
        },
        {
            "name": "estimatedDeliveryDate",
            "baseName": "estimatedDeliveryDate",
            "type": "string"
        },
        {
            "name": "estimatedDeliveryTime",
            "baseName": "estimatedDeliveryTime",
            "type": "string"
        },
        {
            "name": "deliveryDate",
            "baseName": "deliveryDate",
            "type": "string"
        },
        {
            "name": "deliveryTime",
            "baseName": "deliveryTime",
            "type": "string"
        },
        {
            "name": "deliveryLocation",
            "baseName": "deliveryLocation",
            "type": "string"
        },
        {
            "name": "deliveryLocationDescription",
            "baseName": "deliveryLocationDescription",
            "type": "string"
        },
        {
            "name": "signedBy",
            "baseName": "signedBy",
            "type": "string"
        },
        {
            "name": "weight",
            "baseName": "weight",
            "type": "number"
        },
        {
            "name": "weightOUM",
            "baseName": "weightOUM",
            "type": "TrackingResponse.WeightOUMEnum"
        },
        {
            "name": "reattemptDate",
            "baseName": "reattemptDate",
            "type": "string"
        },
        {
            "name": "reattemptTime",
            "baseName": "reattemptTime",
            "type": "string"
        },
        {
            "name": "destinationAddress",
            "baseName": "destinationAddress",
            "type": "TrackingAddress"
        },
        {
            "name": "senderAddress",
            "baseName": "senderAddress",
            "type": "TrackingAddress"
        },
        {
            "name": "scanDetailsList",
            "baseName": "scanDetailsList",
            "type": "Array<TrackingResponseScanDetailsList>"
        }    ];

    static getAttributeTypeMap() {
        return TrackingResponse.attributeTypeMap;
    }
}

export namespace TrackingResponse {
    export enum StatusEnum {
        InTransit = <any> 'In Transit',
        Delivered = <any> 'Delivered',
        Manifest = <any> 'Manifest'
    }
    export enum WeightOUMEnum {
        LBS = <any> 'LBS',
        KGS = <any> 'KGS'
    }
}
