/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export enum UnitOfWeight {
    GM = <any> 'GM',
    OZ = <any> 'OZ',
    LB = <any> 'LB',
    KG = <any> 'KG'
}
