/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Address from './Address';
import AddressSuggestionResponseSuggestions from './AddressSuggestionResponseSuggestions';

/**
 * The AddressSuggestionResponse model module.
 * @module PB.ShippingAPI/model/AddressSuggestionResponse
 * @version 1.0.0
 */
class AddressSuggestionResponse {
    /**
     * Constructs a new <code>AddressSuggestionResponse</code>.
     * @alias module:PB.ShippingAPI/model/AddressSuggestionResponse
     */
    constructor() { 
        
        AddressSuggestionResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AddressSuggestionResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PB.ShippingAPI/model/AddressSuggestionResponse} obj Optional instance to populate.
     * @return {module:PB.ShippingAPI/model/AddressSuggestionResponse} The populated <code>AddressSuggestionResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddressSuggestionResponse();

            if (data.hasOwnProperty('address')) {
                obj['address'] = Address.constructFromObject(data['address']);
            }
            if (data.hasOwnProperty('suggestions')) {
                obj['suggestions'] = AddressSuggestionResponseSuggestions.constructFromObject(data['suggestions']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:PB.ShippingAPI/model/Address} address
 */
AddressSuggestionResponse.prototype['address'] = undefined;

/**
 * @member {module:PB.ShippingAPI/model/AddressSuggestionResponseSuggestions} suggestions
 */
AddressSuggestionResponse.prototype['suggestions'] = undefined;






export default AddressSuggestionResponse;

