/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AddTrackingEventsEvents from './AddTrackingEventsEvents';

/**
 * The AddTrackingEventsReferences model module.
 * @module PB.ShippingAPI/model/AddTrackingEventsReferences
 * @version 1.0.0
 */
class AddTrackingEventsReferences {
    /**
     * Constructs a new <code>AddTrackingEventsReferences</code>.
     * @alias module:PB.ShippingAPI/model/AddTrackingEventsReferences
     */
    constructor() { 
        
        AddTrackingEventsReferences.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AddTrackingEventsReferences</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PB.ShippingAPI/model/AddTrackingEventsReferences} obj Optional instance to populate.
     * @return {module:PB.ShippingAPI/model/AddTrackingEventsReferences} The populated <code>AddTrackingEventsReferences</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddTrackingEventsReferences();

            if (data.hasOwnProperty('referenceType')) {
                obj['referenceType'] = ApiClient.convertToType(data['referenceType'], 'String');
            }
            if (data.hasOwnProperty('referenceValue')) {
                obj['referenceValue'] = ApiClient.convertToType(data['referenceValue'], 'String');
            }
            if (data.hasOwnProperty('events')) {
                obj['events'] = ApiClient.convertToType(data['events'], [AddTrackingEventsEvents]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} referenceType
 */
AddTrackingEventsReferences.prototype['referenceType'] = undefined;

/**
 * @member {String} referenceValue
 */
AddTrackingEventsReferences.prototype['referenceValue'] = undefined;

/**
 * @member {Array.<module:PB.ShippingAPI/model/AddTrackingEventsEvents>} events
 */
AddTrackingEventsReferences.prototype['events'] = undefined;






export default AddTrackingEventsReferences;

