/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AddTrackingEventsEvents model module.
 * @module PB.ShippingAPI/model/AddTrackingEventsEvents
 * @version 1.0.0
 */
class AddTrackingEventsEvents {
    /**
     * Constructs a new <code>AddTrackingEventsEvents</code>.
     * @alias module:PB.ShippingAPI/model/AddTrackingEventsEvents
     */
    constructor() { 
        
        AddTrackingEventsEvents.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AddTrackingEventsEvents</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PB.ShippingAPI/model/AddTrackingEventsEvents} obj Optional instance to populate.
     * @return {module:PB.ShippingAPI/model/AddTrackingEventsEvents} The populated <code>AddTrackingEventsEvents</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddTrackingEventsEvents();

            if (data.hasOwnProperty('eventCode')) {
                obj['eventCode'] = ApiClient.convertToType(data['eventCode'], 'String');
            }
            if (data.hasOwnProperty('carrierEventCode')) {
                obj['carrierEventCode'] = ApiClient.convertToType(data['carrierEventCode'], 'String');
            }
            if (data.hasOwnProperty('eventDate')) {
                obj['eventDate'] = ApiClient.convertToType(data['eventDate'], 'String');
            }
            if (data.hasOwnProperty('eventTime')) {
                obj['eventTime'] = ApiClient.convertToType(data['eventTime'], 'String');
            }
            if (data.hasOwnProperty('eventTimeOffset')) {
                obj['eventTimeOffset'] = ApiClient.convertToType(data['eventTimeOffset'], 'String');
            }
            if (data.hasOwnProperty('eventCity')) {
                obj['eventCity'] = ApiClient.convertToType(data['eventCity'], 'String');
            }
            if (data.hasOwnProperty('eventStateOrProvince')) {
                obj['eventStateOrProvince'] = ApiClient.convertToType(data['eventStateOrProvince'], 'String');
            }
            if (data.hasOwnProperty('postalCode')) {
                obj['postalCode'] = ApiClient.convertToType(data['postalCode'], 'String');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} eventCode
 */
AddTrackingEventsEvents.prototype['eventCode'] = undefined;

/**
 * @member {String} carrierEventCode
 */
AddTrackingEventsEvents.prototype['carrierEventCode'] = undefined;

/**
 * @member {String} eventDate
 */
AddTrackingEventsEvents.prototype['eventDate'] = undefined;

/**
 * @member {String} eventTime
 */
AddTrackingEventsEvents.prototype['eventTime'] = undefined;

/**
 * @member {String} eventTimeOffset
 */
AddTrackingEventsEvents.prototype['eventTimeOffset'] = undefined;

/**
 * @member {String} eventCity
 */
AddTrackingEventsEvents.prototype['eventCity'] = undefined;

/**
 * @member {String} eventStateOrProvince
 */
AddTrackingEventsEvents.prototype['eventStateOrProvince'] = undefined;

/**
 * @member {String} postalCode
 */
AddTrackingEventsEvents.prototype['postalCode'] = undefined;

/**
 * @member {String} country
 */
AddTrackingEventsEvents.prototype['country'] = undefined;






export default AddTrackingEventsEvents;

