/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Errors from './Errors';

/**
 * The CancelShipment model module.
 * @module PB.ShippingAPI/model/CancelShipment
 * @version 1.0.0
 */
class CancelShipment {
    /**
     * Constructs a new <code>CancelShipment</code>.
     * @alias module:PB.ShippingAPI/model/CancelShipment
     */
    constructor() { 
        
        CancelShipment.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CancelShipment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PB.ShippingAPI/model/CancelShipment} obj Optional instance to populate.
     * @return {module:PB.ShippingAPI/model/CancelShipment} The populated <code>CancelShipment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CancelShipment();

            if (data.hasOwnProperty('cancelInitiator')) {
                obj['cancelInitiator'] = ApiClient.convertToType(data['cancelInitiator'], 'String');
            }
            if (data.hasOwnProperty('carrier')) {
                obj['carrier'] = ApiClient.convertToType(data['carrier'], 'String');
            }
            if (data.hasOwnProperty('errorMessages')) {
                obj['errorMessages'] = ApiClient.convertToType(data['errorMessages'], [Errors]);
            }
            if (data.hasOwnProperty('parcelTrackingNumber')) {
                obj['parcelTrackingNumber'] = ApiClient.convertToType(data['parcelTrackingNumber'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('totalCarrierCharge')) {
                obj['totalCarrierCharge'] = ApiClient.convertToType(data['totalCarrierCharge'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} cancelInitiator
 */
CancelShipment.prototype['cancelInitiator'] = undefined;

/**
 * @member {String} carrier
 */
CancelShipment.prototype['carrier'] = undefined;

/**
 * @member {Array.<module:PB.ShippingAPI/model/Errors>} errorMessages
 */
CancelShipment.prototype['errorMessages'] = undefined;

/**
 * @member {String} parcelTrackingNumber
 */
CancelShipment.prototype['parcelTrackingNumber'] = undefined;

/**
 * @member {String} status
 */
CancelShipment.prototype['status'] = undefined;

/**
 * @member {Number} totalCarrierCharge
 */
CancelShipment.prototype['totalCarrierCharge'] = undefined;






export default CancelShipment;

