/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CarrierPayment model module.
 * @module PB.ShippingAPI/model/CarrierPayment
 * @version 1.0.0
 */
class CarrierPayment {
    /**
     * Constructs a new <code>CarrierPayment</code>.
     * @alias module:PB.ShippingAPI/model/CarrierPayment
     * @param party {module:PB.ShippingAPI/model/CarrierPayment.PartyEnum} 
     * @param typeOfCharge {module:PB.ShippingAPI/model/CarrierPayment.TypeOfChargeEnum} 
     */
    constructor(party, typeOfCharge) { 
        
        CarrierPayment.initialize(this, party, typeOfCharge);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, party, typeOfCharge) { 
        obj['party'] = party;
        obj['typeOfCharge'] = typeOfCharge;
    }

    /**
     * Constructs a <code>CarrierPayment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PB.ShippingAPI/model/CarrierPayment} obj Optional instance to populate.
     * @return {module:PB.ShippingAPI/model/CarrierPayment} The populated <code>CarrierPayment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CarrierPayment();

            if (data.hasOwnProperty('accountNumber')) {
                obj['accountNumber'] = ApiClient.convertToType(data['accountNumber'], 'String');
            }
            if (data.hasOwnProperty('countryCode')) {
                obj['countryCode'] = ApiClient.convertToType(data['countryCode'], 'String');
            }
            if (data.hasOwnProperty('party')) {
                obj['party'] = ApiClient.convertToType(data['party'], 'String');
            }
            if (data.hasOwnProperty('postalCode')) {
                obj['postalCode'] = ApiClient.convertToType(data['postalCode'], 'String');
            }
            if (data.hasOwnProperty('typeOfCharge')) {
                obj['typeOfCharge'] = ApiClient.convertToType(data['typeOfCharge'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} accountNumber
 */
CarrierPayment.prototype['accountNumber'] = undefined;

/**
 * @member {String} countryCode
 */
CarrierPayment.prototype['countryCode'] = undefined;

/**
 * @member {module:PB.ShippingAPI/model/CarrierPayment.PartyEnum} party
 */
CarrierPayment.prototype['party'] = undefined;

/**
 * @member {String} postalCode
 */
CarrierPayment.prototype['postalCode'] = undefined;

/**
 * @member {module:PB.ShippingAPI/model/CarrierPayment.TypeOfChargeEnum} typeOfCharge
 */
CarrierPayment.prototype['typeOfCharge'] = undefined;





/**
 * Allowed values for the <code>party</code> property.
 * @enum {String}
 * @readonly
 */
CarrierPayment['PartyEnum'] = {

    /**
     * value: "BILL_RECEIVER"
     * @const
     */
    "RECEIVER": "BILL_RECEIVER",

    /**
     * value: "BILL_SENDER"
     * @const
     */
    "SENDER": "BILL_SENDER",

    /**
     * value: "BILL_THIRD_PARTY"
     * @const
     */
    "THIRD_PARTY": "BILL_THIRD_PARTY",

    /**
     * value: "BILL_RECEIVER_CONTRACT"
     * @const
     */
    "RECEIVER_CONTRACT": "BILL_RECEIVER_CONTRACT"
};


/**
 * Allowed values for the <code>typeOfCharge</code> property.
 * @enum {String}
 * @readonly
 */
CarrierPayment['TypeOfChargeEnum'] = {

    /**
     * value: "TRANSPORTATION_CHARGES"
     * @const
     */
    "TRANSPORTATION_CHARGES": "TRANSPORTATION_CHARGES",

    /**
     * value: "DUTIES_AND_TAXES"
     * @const
     */
    "DUTIES_AND_TAXES": "DUTIES_AND_TAXES",

    /**
     * value: "ALL_CHARGES"
     * @const
     */
    "ALL_CHARGES": "ALL_CHARGES"
};



export default CarrierPayment;

