/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ParcelTypeRules from './ParcelTypeRules';
import Services from './Services';

/**
 * The CarrierRule model module.
 * @module PB.ShippingAPI/model/CarrierRule
 * @version 1.0.0
 */
class CarrierRule {
    /**
     * Constructs a new <code>CarrierRule</code>.
     * @alias module:PB.ShippingAPI/model/CarrierRule
     */
    constructor() { 
        
        CarrierRule.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CarrierRule</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PB.ShippingAPI/model/CarrierRule} obj Optional instance to populate.
     * @return {module:PB.ShippingAPI/model/CarrierRule} The populated <code>CarrierRule</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CarrierRule();

            if (data.hasOwnProperty('serviceId')) {
                obj['serviceId'] = Services.constructFromObject(data['serviceId']);
            }
            if (data.hasOwnProperty('brandedName')) {
                obj['brandedName'] = ApiClient.convertToType(data['brandedName'], 'String');
            }
            if (data.hasOwnProperty('parcelTypeRules')) {
                obj['parcelTypeRules'] = ApiClient.convertToType(data['parcelTypeRules'], [ParcelTypeRules]);
            }
            if (data.hasOwnProperty('parameters')) {
                obj['parameters'] = ApiClient.convertToType(data['parameters'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:PB.ShippingAPI/model/Services} serviceId
 */
CarrierRule.prototype['serviceId'] = undefined;

/**
 * @member {String} brandedName
 */
CarrierRule.prototype['brandedName'] = undefined;

/**
 * @member {Array.<module:PB.ShippingAPI/model/ParcelTypeRules>} parcelTypeRules
 */
CarrierRule.prototype['parcelTypeRules'] = undefined;

/**
 * @member {Array.<String>} parameters
 */
CarrierRule.prototype['parameters'] = undefined;






export default CarrierRule;

