/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CarrierFacilityRequestAddress model module.
 * @module PB.ShippingAPI/model/CarrierFacilityRequestAddress
 * @version 1.0.0
 */
class CarrierFacilityRequestAddress {
    /**
     * Constructs a new <code>CarrierFacilityRequestAddress</code>.
     * @alias module:PB.ShippingAPI/model/CarrierFacilityRequestAddress
     */
    constructor() { 
        
        CarrierFacilityRequestAddress.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CarrierFacilityRequestAddress</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PB.ShippingAPI/model/CarrierFacilityRequestAddress} obj Optional instance to populate.
     * @return {module:PB.ShippingAPI/model/CarrierFacilityRequestAddress} The populated <code>CarrierFacilityRequestAddress</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CarrierFacilityRequestAddress();

            if (data.hasOwnProperty('addressLines')) {
                obj['addressLines'] = ApiClient.convertToType(data['addressLines'], ['String']);
            }
            if (data.hasOwnProperty('cityTown')) {
                obj['cityTown'] = ApiClient.convertToType(data['cityTown'], 'String');
            }
            if (data.hasOwnProperty('stateProvince')) {
                obj['stateProvince'] = ApiClient.convertToType(data['stateProvince'], 'String');
            }
            if (data.hasOwnProperty('countryCode')) {
                obj['countryCode'] = ApiClient.convertToType(data['countryCode'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} addressLines
 */
CarrierFacilityRequestAddress.prototype['addressLines'] = undefined;

/**
 * @member {String} cityTown
 */
CarrierFacilityRequestAddress.prototype['cityTown'] = undefined;

/**
 * @member {String} stateProvince
 */
CarrierFacilityRequestAddress.prototype['stateProvince'] = undefined;

/**
 * @member {String} countryCode
 */
CarrierFacilityRequestAddress.prototype['countryCode'] = undefined;






export default CarrierFacilityRequestAddress;

