/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class Carrier.
* @enum {}
* @readonly
*/
export default class Carrier {
    
        /**
         * value: "USPS"
         * @const
         */
        "USPS" = "USPS";

    
        /**
         * value: "PBPRESORT"
         * @const
         */
        "PBPRESORT" = "PBPRESORT";

    
        /**
         * value: "NEWGISTICS"
         * @const
         */
        "NEWGISTICS" = "NEWGISTICS";

    
        /**
         * value: "PBI"
         * @const
         */
        "PBI" = "PBI";

    
        /**
         * value: "FEDEX"
         * @const
         */
        "FEDEX" = "FEDEX";

    
        /**
         * value: "USP"
         * @const
         */
        "USP" = "USP";

    

    /**
    * Returns a <code>Carrier</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:PB.ShippingAPI/model/Carrier} The enum <code>Carrier</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

