/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ContainerManifestResponseData model module.
 * @module PB.ShippingAPI/model/ContainerManifestResponseData
 * @version 1.0.0
 */
class ContainerManifestResponseData {
    /**
     * Constructs a new <code>ContainerManifestResponseData</code>.
     * @alias module:PB.ShippingAPI/model/ContainerManifestResponseData
     */
    constructor() { 
        
        ContainerManifestResponseData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ContainerManifestResponseData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PB.ShippingAPI/model/ContainerManifestResponseData} obj Optional instance to populate.
     * @return {module:PB.ShippingAPI/model/ContainerManifestResponseData} The populated <code>ContainerManifestResponseData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContainerManifestResponseData();

            if (data.hasOwnProperty('pbContainerId')) {
                obj['pbContainerId'] = ApiClient.convertToType(data['pbContainerId'], 'String');
            }
            if (data.hasOwnProperty('labelData')) {
                obj['labelData'] = ApiClient.convertToType(data['labelData'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} pbContainerId
 */
ContainerManifestResponseData.prototype['pbContainerId'] = undefined;

/**
 * @member {String} labelData
 */
ContainerManifestResponseData.prototype['labelData'] = undefined;






export default ContainerManifestResponseData;

