/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ContainerManifestResponseData from './ContainerManifestResponseData';

/**
 * The ContainerManifestResponse model module.
 * @module PB.ShippingAPI/model/ContainerManifestResponse
 * @version 1.0.0
 */
class ContainerManifestResponse {
    /**
     * Constructs a new <code>ContainerManifestResponse</code>.
     * @alias module:PB.ShippingAPI/model/ContainerManifestResponse
     */
    constructor() { 
        
        ContainerManifestResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ContainerManifestResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PB.ShippingAPI/model/ContainerManifestResponse} obj Optional instance to populate.
     * @return {module:PB.ShippingAPI/model/ContainerManifestResponse} The populated <code>ContainerManifestResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContainerManifestResponse();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ContainerManifestResponseData.constructFromObject(data['data']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:PB.ShippingAPI/model/ContainerManifestResponseData} data
 */
ContainerManifestResponse.prototype['data'] = undefined;






export default ContainerManifestResponse;

