/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CrossBorderQuotesErrorsQuote from './CrossBorderQuotesErrorsQuote';

/**
 * The CrossBorderQuotesErrors model module.
 * @module PB.ShippingAPI/model/CrossBorderQuotesErrors
 * @version 1.0.0
 */
class CrossBorderQuotesErrors {
    /**
     * Constructs a new <code>CrossBorderQuotesErrors</code>.
     * @alias module:PB.ShippingAPI/model/CrossBorderQuotesErrors
     */
    constructor() { 
        
        CrossBorderQuotesErrors.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CrossBorderQuotesErrors</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PB.ShippingAPI/model/CrossBorderQuotesErrors} obj Optional instance to populate.
     * @return {module:PB.ShippingAPI/model/CrossBorderQuotesErrors} The populated <code>CrossBorderQuotesErrors</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CrossBorderQuotesErrors();

            if (data.hasOwnProperty('quote')) {
                obj['quote'] = ApiClient.convertToType(data['quote'], [CrossBorderQuotesErrorsQuote]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:PB.ShippingAPI/model/CrossBorderQuotesErrorsQuote>} quote
 */
CrossBorderQuotesErrors.prototype['quote'] = undefined;






export default CrossBorderQuotesErrors;

