/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CrossBorderQuotesErrorsUnitErrors model module.
 * @module PB.ShippingAPI/model/CrossBorderQuotesErrorsUnitErrors
 * @version 1.0.0
 */
class CrossBorderQuotesErrorsUnitErrors {
    /**
     * Constructs a new <code>CrossBorderQuotesErrorsUnitErrors</code>.
     * @alias module:PB.ShippingAPI/model/CrossBorderQuotesErrorsUnitErrors
     */
    constructor() { 
        
        CrossBorderQuotesErrorsUnitErrors.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CrossBorderQuotesErrorsUnitErrors</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PB.ShippingAPI/model/CrossBorderQuotesErrorsUnitErrors} obj Optional instance to populate.
     * @return {module:PB.ShippingAPI/model/CrossBorderQuotesErrorsUnitErrors} The populated <code>CrossBorderQuotesErrorsUnitErrors</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CrossBorderQuotesErrorsUnitErrors();

            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'Number');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} error
 */
CrossBorderQuotesErrorsUnitErrors.prototype['error'] = undefined;

/**
 * @member {String} message
 */
CrossBorderQuotesErrorsUnitErrors.prototype['message'] = undefined;






export default CrossBorderQuotesErrorsUnitErrors;

