/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CrossBorderQuotesRequestDescriptions from './CrossBorderQuotesRequestDescriptions';

/**
 * The CrossBorderQuotesRequestCategories model module.
 * @module PB.ShippingAPI/model/CrossBorderQuotesRequestCategories
 * @version 1.0.0
 */
class CrossBorderQuotesRequestCategories {
    /**
     * Constructs a new <code>CrossBorderQuotesRequestCategories</code>.
     * @alias module:PB.ShippingAPI/model/CrossBorderQuotesRequestCategories
     */
    constructor() { 
        
        CrossBorderQuotesRequestCategories.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CrossBorderQuotesRequestCategories</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PB.ShippingAPI/model/CrossBorderQuotesRequestCategories} obj Optional instance to populate.
     * @return {module:PB.ShippingAPI/model/CrossBorderQuotesRequestCategories} The populated <code>CrossBorderQuotesRequestCategories</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CrossBorderQuotesRequestCategories();

            if (data.hasOwnProperty('categoryCode')) {
                obj['categoryCode'] = ApiClient.convertToType(data['categoryCode'], 'String');
            }
            if (data.hasOwnProperty('descriptions')) {
                obj['descriptions'] = ApiClient.convertToType(data['descriptions'], [CrossBorderQuotesRequestDescriptions]);
            }
            if (data.hasOwnProperty('parentCategoryCode')) {
                obj['parentCategoryCode'] = ApiClient.convertToType(data['parentCategoryCode'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} categoryCode
 */
CrossBorderQuotesRequestCategories.prototype['categoryCode'] = undefined;

/**
 * @member {Array.<module:PB.ShippingAPI/model/CrossBorderQuotesRequestDescriptions>} descriptions
 */
CrossBorderQuotesRequestCategories.prototype['descriptions'] = undefined;

/**
 * @member {String} parentCategoryCode
 */
CrossBorderQuotesRequestCategories.prototype['parentCategoryCode'] = undefined;

/**
 * @member {String} url
 */
CrossBorderQuotesRequestCategories.prototype['url'] = undefined;






export default CrossBorderQuotesRequestCategories;

