/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CrossBorderQuotesResponseUnitRatesDeliveryCommitment from './CrossBorderQuotesResponseUnitRatesDeliveryCommitment';

/**
 * The CrossBorderQuotesResponseLineRates model module.
 * @module PB.ShippingAPI/model/CrossBorderQuotesResponseLineRates
 * @version 1.0.0
 */
class CrossBorderQuotesResponseLineRates {
    /**
     * Constructs a new <code>CrossBorderQuotesResponseLineRates</code>.
     * @alias module:PB.ShippingAPI/model/CrossBorderQuotesResponseLineRates
     */
    constructor() { 
        
        CrossBorderQuotesResponseLineRates.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CrossBorderQuotesResponseLineRates</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PB.ShippingAPI/model/CrossBorderQuotesResponseLineRates} obj Optional instance to populate.
     * @return {module:PB.ShippingAPI/model/CrossBorderQuotesResponseLineRates} The populated <code>CrossBorderQuotesResponseLineRates</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CrossBorderQuotesResponseLineRates();

            if (data.hasOwnProperty('linePrice')) {
                obj['linePrice'] = ApiClient.convertToType(data['linePrice'], 'Number');
            }
            if (data.hasOwnProperty('totalTaxAmount')) {
                obj['totalTaxAmount'] = ApiClient.convertToType(data['totalTaxAmount'], 'Number');
            }
            if (data.hasOwnProperty('totalDutyAmount')) {
                obj['totalDutyAmount'] = ApiClient.convertToType(data['totalDutyAmount'], 'Number');
            }
            if (data.hasOwnProperty('serviceId')) {
                obj['serviceId'] = ApiClient.convertToType(data['serviceId'], 'String');
            }
            if (data.hasOwnProperty('baseCharge')) {
                obj['baseCharge'] = ApiClient.convertToType(data['baseCharge'], 'Number');
            }
            if (data.hasOwnProperty('deliveryCommitment')) {
                obj['deliveryCommitment'] = CrossBorderQuotesResponseUnitRatesDeliveryCommitment.constructFromObject(data['deliveryCommitment']);
            }
            if (data.hasOwnProperty('totalCarrierCharge')) {
                obj['totalCarrierCharge'] = ApiClient.convertToType(data['totalCarrierCharge'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} linePrice
 */
CrossBorderQuotesResponseLineRates.prototype['linePrice'] = undefined;

/**
 * @member {Number} totalTaxAmount
 */
CrossBorderQuotesResponseLineRates.prototype['totalTaxAmount'] = undefined;

/**
 * @member {Number} totalDutyAmount
 */
CrossBorderQuotesResponseLineRates.prototype['totalDutyAmount'] = undefined;

/**
 * @member {String} serviceId
 */
CrossBorderQuotesResponseLineRates.prototype['serviceId'] = undefined;

/**
 * @member {Number} baseCharge
 */
CrossBorderQuotesResponseLineRates.prototype['baseCharge'] = undefined;

/**
 * @member {module:PB.ShippingAPI/model/CrossBorderQuotesResponseUnitRatesDeliveryCommitment} deliveryCommitment
 */
CrossBorderQuotesResponseLineRates.prototype['deliveryCommitment'] = undefined;

/**
 * @member {Number} totalCarrierCharge
 */
CrossBorderQuotesResponseLineRates.prototype['totalCarrierCharge'] = undefined;






export default CrossBorderQuotesResponseLineRates;

