/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CrossBorderQuotesRequestPricingCodPrice from './CrossBorderQuotesRequestPricingCodPrice';

/**
 * The CrossBorderQuotesRequestPricing model module.
 * @module PB.ShippingAPI/model/CrossBorderQuotesRequestPricing
 * @version 1.0.0
 */
class CrossBorderQuotesRequestPricing {
    /**
     * Constructs a new <code>CrossBorderQuotesRequestPricing</code>.
     * @alias module:PB.ShippingAPI/model/CrossBorderQuotesRequestPricing
     */
    constructor() { 
        
        CrossBorderQuotesRequestPricing.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CrossBorderQuotesRequestPricing</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PB.ShippingAPI/model/CrossBorderQuotesRequestPricing} obj Optional instance to populate.
     * @return {module:PB.ShippingAPI/model/CrossBorderQuotesRequestPricing} The populated <code>CrossBorderQuotesRequestPricing</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CrossBorderQuotesRequestPricing();

            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('codPrice')) {
                obj['codPrice'] = ApiClient.convertToType(data['codPrice'], [CrossBorderQuotesRequestPricingCodPrice]);
            }
            if (data.hasOwnProperty('dutiableValue')) {
                obj['dutiableValue'] = ApiClient.convertToType(data['dutiableValue'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} price
 */
CrossBorderQuotesRequestPricing.prototype['price'] = undefined;

/**
 * @member {Array.<module:PB.ShippingAPI/model/CrossBorderQuotesRequestPricingCodPrice>} codPrice
 */
CrossBorderQuotesRequestPricing.prototype['codPrice'] = undefined;

/**
 * @member {Number} dutiableValue
 */
CrossBorderQuotesRequestPricing.prototype['dutiableValue'] = undefined;






export default CrossBorderQuotesRequestPricing;

