/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CrossBorderQuotesRequestDescriptions model module.
 * @module PB.ShippingAPI/model/CrossBorderQuotesRequestDescriptions
 * @version 1.0.0
 */
class CrossBorderQuotesRequestDescriptions {
    /**
     * Constructs a new <code>CrossBorderQuotesRequestDescriptions</code>.
     * @alias module:PB.ShippingAPI/model/CrossBorderQuotesRequestDescriptions
     */
    constructor() { 
        
        CrossBorderQuotesRequestDescriptions.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CrossBorderQuotesRequestDescriptions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PB.ShippingAPI/model/CrossBorderQuotesRequestDescriptions} obj Optional instance to populate.
     * @return {module:PB.ShippingAPI/model/CrossBorderQuotesRequestDescriptions} The populated <code>CrossBorderQuotesRequestDescriptions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CrossBorderQuotesRequestDescriptions();

            if (data.hasOwnProperty('locale')) {
                obj['locale'] = ApiClient.convertToType(data['locale'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('parentsNames')) {
                obj['parentsNames'] = ApiClient.convertToType(data['parentsNames'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} locale
 */
CrossBorderQuotesRequestDescriptions.prototype['locale'] = undefined;

/**
 * @member {String} name
 */
CrossBorderQuotesRequestDescriptions.prototype['name'] = undefined;

/**
 * @member {Array.<String>} parentsNames
 */
CrossBorderQuotesRequestDescriptions.prototype['parentsNames'] = undefined;






export default CrossBorderQuotesRequestDescriptions;

