/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Address from './Address';
import ParcelWeight from './ParcelWeight';

/**
 * The CustomsItem model module.
 * @module PB.ShippingAPI/model/CustomsItem
 * @version 1.0.0
 */
class CustomsItem {
    /**
     * Constructs a new <code>CustomsItem</code>.
     * @alias module:PB.ShippingAPI/model/CustomsItem
     * @param description {String} 
     * @param originCountryCode {String} 
     * @param quantity {Number} 
     * @param unitPrice {Number} 
     * @param unitWeight {module:PB.ShippingAPI/model/ParcelWeight} 
     */
    constructor(description, originCountryCode, quantity, unitPrice, unitWeight) { 
        
        CustomsItem.initialize(this, description, originCountryCode, quantity, unitPrice, unitWeight);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, description, originCountryCode, quantity, unitPrice, unitWeight) { 
        obj['description'] = description;
        obj['originCountryCode'] = originCountryCode;
        obj['quantity'] = quantity;
        obj['unitPrice'] = unitPrice;
        obj['unitWeight'] = unitWeight;
    }

    /**
     * Constructs a <code>CustomsItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PB.ShippingAPI/model/CustomsItem} obj Optional instance to populate.
     * @return {module:PB.ShippingAPI/model/CustomsItem} The populated <code>CustomsItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomsItem();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('hSTariffCode')) {
                obj['hSTariffCode'] = ApiClient.convertToType(data['hSTariffCode'], 'String');
            }
            if (data.hasOwnProperty('netCostMethod')) {
                obj['netCostMethod'] = ApiClient.convertToType(data['netCostMethod'], 'String');
            }
            if (data.hasOwnProperty('originCountryCode')) {
                obj['originCountryCode'] = ApiClient.convertToType(data['originCountryCode'], 'String');
            }
            if (data.hasOwnProperty('originStateProvince')) {
                obj['originStateProvince'] = ApiClient.convertToType(data['originStateProvince'], 'String');
            }
            if (data.hasOwnProperty('preferenceCriterion')) {
                obj['preferenceCriterion'] = ApiClient.convertToType(data['preferenceCriterion'], 'String');
            }
            if (data.hasOwnProperty('producerAddress')) {
                obj['producerAddress'] = Address.constructFromObject(data['producerAddress']);
            }
            if (data.hasOwnProperty('producerDetermination')) {
                obj['producerDetermination'] = ApiClient.convertToType(data['producerDetermination'], 'String');
            }
            if (data.hasOwnProperty('producerId')) {
                obj['producerId'] = ApiClient.convertToType(data['producerId'], 'String');
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
            if (data.hasOwnProperty('quantityUOM')) {
                obj['quantityUOM'] = ApiClient.convertToType(data['quantityUOM'], 'String');
            }
            if (data.hasOwnProperty('unitPrice')) {
                obj['unitPrice'] = ApiClient.convertToType(data['unitPrice'], 'Number');
            }
            if (data.hasOwnProperty('unitWeight')) {
                obj['unitWeight'] = ParcelWeight.constructFromObject(data['unitWeight']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} description
 */
CustomsItem.prototype['description'] = undefined;

/**
 * @member {String} hSTariffCode
 */
CustomsItem.prototype['hSTariffCode'] = undefined;

/**
 * @member {module:PB.ShippingAPI/model/CustomsItem.NetCostMethodEnum} netCostMethod
 */
CustomsItem.prototype['netCostMethod'] = undefined;

/**
 * @member {String} originCountryCode
 */
CustomsItem.prototype['originCountryCode'] = undefined;

/**
 * @member {String} originStateProvince
 */
CustomsItem.prototype['originStateProvince'] = undefined;

/**
 * @member {module:PB.ShippingAPI/model/CustomsItem.PreferenceCriterionEnum} preferenceCriterion
 */
CustomsItem.prototype['preferenceCriterion'] = undefined;

/**
 * @member {module:PB.ShippingAPI/model/Address} producerAddress
 */
CustomsItem.prototype['producerAddress'] = undefined;

/**
 * @member {module:PB.ShippingAPI/model/CustomsItem.ProducerDeterminationEnum} producerDetermination
 */
CustomsItem.prototype['producerDetermination'] = undefined;

/**
 * @member {String} producerId
 */
CustomsItem.prototype['producerId'] = undefined;

/**
 * @member {Number} quantity
 */
CustomsItem.prototype['quantity'] = undefined;

/**
 * @member {String} quantityUOM
 */
CustomsItem.prototype['quantityUOM'] = undefined;

/**
 * @member {Number} unitPrice
 */
CustomsItem.prototype['unitPrice'] = undefined;

/**
 * @member {module:PB.ShippingAPI/model/ParcelWeight} unitWeight
 */
CustomsItem.prototype['unitWeight'] = undefined;





/**
 * Allowed values for the <code>netCostMethod</code> property.
 * @enum {String}
 * @readonly
 */
CustomsItem['NetCostMethodEnum'] = {

    /**
     * value: "NO_NET_COST"
     * @const
     */
    "NO_NET_COST": "NO_NET_COST",

    /**
     * value: "NET_COST"
     * @const
     */
    "NET_COST": "NET_COST"
};


/**
 * Allowed values for the <code>preferenceCriterion</code> property.
 * @enum {String}
 * @readonly
 */
CustomsItem['PreferenceCriterionEnum'] = {

    /**
     * value: "A"
     * @const
     */
    "A": "A",

    /**
     * value: "B"
     * @const
     */
    "B": "B",

    /**
     * value: "C"
     * @const
     */
    "C": "C",

    /**
     * value: "D"
     * @const
     */
    "D": "D",

    /**
     * value: "E"
     * @const
     */
    "E": "E",

    /**
     * value: "F"
     * @const
     */
    "F": "F"
};


/**
 * Allowed values for the <code>producerDetermination</code> property.
 * @enum {String}
 * @readonly
 */
CustomsItem['ProducerDeterminationEnum'] = {

    /**
     * value: "NO_1"
     * @const
     */
    "NO_1": "NO_1",

    /**
     * value: "NO_2"
     * @const
     */
    "NO_2": "NO_2",

    /**
     * value: "NO_3"
     * @const
     */
    "NO_3": "NO_3",

    /**
     * value: "PD_YES"
     * @const
     */
    "PD_YES": "PD_YES"
};



export default CustomsItem;

