/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeliveryCommitment model module.
 * @module PB.ShippingAPI/model/DeliveryCommitment
 * @version 1.0.0
 */
class DeliveryCommitment {
    /**
     * Constructs a new <code>DeliveryCommitment</code>.
     * @alias module:PB.ShippingAPI/model/DeliveryCommitment
     */
    constructor() { 
        
        DeliveryCommitment.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DeliveryCommitment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PB.ShippingAPI/model/DeliveryCommitment} obj Optional instance to populate.
     * @return {module:PB.ShippingAPI/model/DeliveryCommitment} The populated <code>DeliveryCommitment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeliveryCommitment();

            if (data.hasOwnProperty('additionalDetails')) {
                obj['additionalDetails'] = ApiClient.convertToType(data['additionalDetails'], 'String');
            }
            if (data.hasOwnProperty('estimatedDeliveryDateTime')) {
                obj['estimatedDeliveryDateTime'] = ApiClient.convertToType(data['estimatedDeliveryDateTime'], 'String');
            }
            if (data.hasOwnProperty('guarantee')) {
                obj['guarantee'] = ApiClient.convertToType(data['guarantee'], 'String');
            }
            if (data.hasOwnProperty('maxEstimatedNumberOfDays')) {
                obj['maxEstimatedNumberOfDays'] = ApiClient.convertToType(data['maxEstimatedNumberOfDays'], 'String');
            }
            if (data.hasOwnProperty('minEstimatedNumberOfDays')) {
                obj['minEstimatedNumberOfDays'] = ApiClient.convertToType(data['minEstimatedNumberOfDays'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} additionalDetails
 */
DeliveryCommitment.prototype['additionalDetails'] = undefined;

/**
 * @member {String} estimatedDeliveryDateTime
 */
DeliveryCommitment.prototype['estimatedDeliveryDateTime'] = undefined;

/**
 * @member {String} guarantee
 */
DeliveryCommitment.prototype['guarantee'] = undefined;

/**
 * @member {String} maxEstimatedNumberOfDays
 */
DeliveryCommitment.prototype['maxEstimatedNumberOfDays'] = undefined;

/**
 * @member {String} minEstimatedNumberOfDays
 */
DeliveryCommitment.prototype['minEstimatedNumberOfDays'] = undefined;






export default DeliveryCommitment;

