/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DimensionRulesMaxParcelDimensions model module.
 * @module PB.ShippingAPI/model/DimensionRulesMaxParcelDimensions
 * @version 1.0.0
 */
class DimensionRulesMaxParcelDimensions {
    /**
     * Constructs a new <code>DimensionRulesMaxParcelDimensions</code>.
     * @alias module:PB.ShippingAPI/model/DimensionRulesMaxParcelDimensions
     */
    constructor() { 
        
        DimensionRulesMaxParcelDimensions.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DimensionRulesMaxParcelDimensions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PB.ShippingAPI/model/DimensionRulesMaxParcelDimensions} obj Optional instance to populate.
     * @return {module:PB.ShippingAPI/model/DimensionRulesMaxParcelDimensions} The populated <code>DimensionRulesMaxParcelDimensions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DimensionRulesMaxParcelDimensions();

            if (data.hasOwnProperty('length')) {
                obj['length'] = ApiClient.convertToType(data['length'], 'Number');
            }
            if (data.hasOwnProperty('width')) {
                obj['width'] = ApiClient.convertToType(data['width'], 'Number');
            }
            if (data.hasOwnProperty('height')) {
                obj['height'] = ApiClient.convertToType(data['height'], 'Number');
            }
            if (data.hasOwnProperty('unitOfMeasurement')) {
                obj['unitOfMeasurement'] = ApiClient.convertToType(data['unitOfMeasurement'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} length
 */
DimensionRulesMaxParcelDimensions.prototype['length'] = undefined;

/**
 * @member {Number} width
 */
DimensionRulesMaxParcelDimensions.prototype['width'] = undefined;

/**
 * @member {Number} height
 */
DimensionRulesMaxParcelDimensions.prototype['height'] = undefined;

/**
 * @member {String} unitOfMeasurement
 */
DimensionRulesMaxParcelDimensions.prototype['unitOfMeasurement'] = undefined;






export default DimensionRulesMaxParcelDimensions;

