/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DocumentPage model module.
 * @module PB.ShippingAPI/model/DocumentPage
 * @version 1.0.0
 */
class DocumentPage {
    /**
     * Constructs a new <code>DocumentPage</code>.
     * @alias module:PB.ShippingAPI/model/DocumentPage
     */
    constructor() { 
        
        DocumentPage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DocumentPage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PB.ShippingAPI/model/DocumentPage} obj Optional instance to populate.
     * @return {module:PB.ShippingAPI/model/DocumentPage} The populated <code>DocumentPage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DocumentPage();

            if (data.hasOwnProperty('contents')) {
                obj['contents'] = ApiClient.convertToType(data['contents'], 'String');
            }
        }
        return obj;
    }


}

/**
 * base64
 * @member {String} contents
 */
DocumentPage.prototype['contents'] = undefined;






export default DocumentPage;

