/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InfectiousSubstanceContact model module.
 * @module PB.ShippingAPI/model/InfectiousSubstanceContact
 * @version 1.0.0
 */
class InfectiousSubstanceContact {
    /**
     * Constructs a new <code>InfectiousSubstanceContact</code>.
     * @alias module:PB.ShippingAPI/model/InfectiousSubstanceContact
     */
    constructor() { 
        
        InfectiousSubstanceContact.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InfectiousSubstanceContact</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PB.ShippingAPI/model/InfectiousSubstanceContact} obj Optional instance to populate.
     * @return {module:PB.ShippingAPI/model/InfectiousSubstanceContact} The populated <code>InfectiousSubstanceContact</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InfectiousSubstanceContact();

            if (data.hasOwnProperty('companyName')) {
                obj['companyName'] = ApiClient.convertToType(data['companyName'], 'String');
            }
            if (data.hasOwnProperty('contactId')) {
                obj['contactId'] = ApiClient.convertToType(data['contactId'], 'String');
            }
            if (data.hasOwnProperty('emailAddress')) {
                obj['emailAddress'] = ApiClient.convertToType(data['emailAddress'], 'String');
            }
            if (data.hasOwnProperty('personName')) {
                obj['personName'] = ApiClient.convertToType(data['personName'], 'String');
            }
            if (data.hasOwnProperty('phoneNumber')) {
                obj['phoneNumber'] = ApiClient.convertToType(data['phoneNumber'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} companyName
 */
InfectiousSubstanceContact.prototype['companyName'] = undefined;

/**
 * @member {String} contactId
 */
InfectiousSubstanceContact.prototype['contactId'] = undefined;

/**
 * @member {String} emailAddress
 */
InfectiousSubstanceContact.prototype['emailAddress'] = undefined;

/**
 * @member {String} personName
 */
InfectiousSubstanceContact.prototype['personName'] = undefined;

/**
 * @member {String} phoneNumber
 */
InfectiousSubstanceContact.prototype['phoneNumber'] = undefined;






export default InfectiousSubstanceContact;

