/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Address from './Address';

/**
 * The ParcelProtectionCreateRequestShipmentInfoConsigneeInfo model module.
 * @module PB.ShippingAPI/model/ParcelProtectionCreateRequestShipmentInfoConsigneeInfo
 * @version 1.0.0
 */
class ParcelProtectionCreateRequestShipmentInfoConsigneeInfo {
    /**
     * Constructs a new <code>ParcelProtectionCreateRequestShipmentInfoConsigneeInfo</code>.
     * @alias module:PB.ShippingAPI/model/ParcelProtectionCreateRequestShipmentInfoConsigneeInfo
     */
    constructor() { 
        
        ParcelProtectionCreateRequestShipmentInfoConsigneeInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ParcelProtectionCreateRequestShipmentInfoConsigneeInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PB.ShippingAPI/model/ParcelProtectionCreateRequestShipmentInfoConsigneeInfo} obj Optional instance to populate.
     * @return {module:PB.ShippingAPI/model/ParcelProtectionCreateRequestShipmentInfoConsigneeInfo} The populated <code>ParcelProtectionCreateRequestShipmentInfoConsigneeInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ParcelProtectionCreateRequestShipmentInfoConsigneeInfo();

            if (data.hasOwnProperty('address')) {
                obj['address'] = Address.constructFromObject(data['address']);
            }
            if (data.hasOwnProperty('companyName')) {
                obj['companyName'] = ApiClient.convertToType(data['companyName'], 'String');
            }
            if (data.hasOwnProperty('familyName')) {
                obj['familyName'] = ApiClient.convertToType(data['familyName'], 'String');
            }
            if (data.hasOwnProperty('givenName')) {
                obj['givenName'] = ApiClient.convertToType(data['givenName'], 'String');
            }
            if (data.hasOwnProperty('middleName')) {
                obj['middleName'] = ApiClient.convertToType(data['middleName'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('phoneNumbers')) {
                obj['phoneNumbers'] = ApiClient.convertToType(data['phoneNumbers'], [Object]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:PB.ShippingAPI/model/Address} address
 */
ParcelProtectionCreateRequestShipmentInfoConsigneeInfo.prototype['address'] = undefined;

/**
 * @member {String} companyName
 */
ParcelProtectionCreateRequestShipmentInfoConsigneeInfo.prototype['companyName'] = undefined;

/**
 * @member {String} familyName
 */
ParcelProtectionCreateRequestShipmentInfoConsigneeInfo.prototype['familyName'] = undefined;

/**
 * @member {String} givenName
 */
ParcelProtectionCreateRequestShipmentInfoConsigneeInfo.prototype['givenName'] = undefined;

/**
 * @member {String} middleName
 */
ParcelProtectionCreateRequestShipmentInfoConsigneeInfo.prototype['middleName'] = undefined;

/**
 * @member {String} email
 */
ParcelProtectionCreateRequestShipmentInfoConsigneeInfo.prototype['email'] = undefined;

/**
 * @member {Array.<Object>} phoneNumbers
 */
ParcelProtectionCreateRequestShipmentInfoConsigneeInfo.prototype['phoneNumbers'] = undefined;






export default ParcelProtectionCreateRequestShipmentInfoConsigneeInfo;

