/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ParcelType.
* @enum {}
* @readonly
*/
export default class ParcelType {
    
        /**
         * value: "FLAT"
         * @const
         */
        "FLAT" = "FLAT";

    
        /**
         * value: "LETTER"
         * @const
         */
        "LETTER" = "LETTER";

    
        /**
         * value: "FRE"
         * @const
         */
        "FRE" = "FRE";

    
        /**
         * value: "LGENV"
         * @const
         */
        "LGENV" = "LGENV";

    
        /**
         * value: "LGLFRENV"
         * @const
         */
        "LGLFRENV" = "LGLFRENV";

    
        /**
         * value: "PFRENV"
         * @const
         */
        "PFRENV" = "PFRENV";

    
        /**
         * value: "FRB"
         * @const
         */
        "FRB" = "FRB";

    
        /**
         * value: "LFRB"
         * @const
         */
        "LFRB" = "LFRB";

    
        /**
         * value: "DVDBOX"
         * @const
         */
        "DVDBOX" = "DVDBOX";

    
        /**
         * value: "VIDEOBOX"
         * @const
         */
        "VIDEOBOX" = "VIDEOBOX";

    
        /**
         * value: "MLFRB"
         * @const
         */
        "MLFRB" = "MLFRB";

    
        /**
         * value: "RBA"
         * @const
         */
        "RBA" = "RBA";

    
        /**
         * value: "RBB"
         * @const
         */
        "RBB" = "RBB";

    
        /**
         * value: "LP"
         * @const
         */
        "LP" = "LP";

    
        /**
         * value: "SACK"
         * @const
         */
        "SACK" = "SACK";

    
        /**
         * value: "SOFTPACK"
         * @const
         */
        "SOFTPACK" = "SOFTPACK";

    
        /**
         * value: "MIX"
         * @const
         */
        "MIX" = "MIX";

    
        /**
         * value: "LTR"
         * @const
         */
        "LTR" = "LTR";

    
        /**
         * value: "NMLETTER"
         * @const
         */
        "NMLETTER" = "NMLETTER";

    
        /**
         * value: "NMLTR"
         * @const
         */
        "NMLTR" = "NMLTR";

    
        /**
         * value: "IRRPKG"
         * @const
         */
        "IRRPKG" = "IRRPKG";

    
        /**
         * value: "SFRB"
         * @const
         */
        "SFRB" = "SFRB";

    
        /**
         * value: "EMMTB"
         * @const
         */
        "EMMTB" = "EMMTB";

    
        /**
         * value: "FTB"
         * @const
         */
        "FTB" = "FTB";

    
        /**
         * value: "FTTB"
         * @const
         */
        "FTTB" = "FTTB";

    
        /**
         * value: "HTB"
         * @const
         */
        "HTB" = "HTB";

    
        /**
         * value: "PACK"
         * @const
         */
        "PACK" = "PACK";

    
        /**
         * value: "BOX"
         * @const
         */
        "BOX" = "BOX";

    
        /**
         * value: "SMALL_EXP_BOX"
         * @const
         */
        "SMALL_EXP_BOX" = "SMALL_EXP_BOX";

    
        /**
         * value: "MED_EXP_BOX"
         * @const
         */
        "MED_EXP_BOX" = "MED_EXP_BOX";

    
        /**
         * value: "LG_EXP_BOX"
         * @const
         */
        "LG_EXP_BOX" = "LG_EXP_BOX";

    
        /**
         * value: "EXTRA_LG_EXP_BOX"
         * @const
         */
        "EXTRA_LG_EXP_BOX" = "EXTRA_LG_EXP_BOX";

    
        /**
         * value: "TUBE"
         * @const
         */
        "TUBE" = "TUBE";

    
        /**
         * value: "25KG"
         * @const
         */
        "25KG" = "25KG";

    
        /**
         * value: "10KG"
         * @const
         */
        "10KG" = "10KG";

    
        /**
         * value: "PKG"
         * @const
         */
        "PKG" = "PKG";

    

    /**
    * Returns a <code>ParcelType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:PB.ShippingAPI/model/ParcelType} The enum <code>ParcelType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

