/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ParcelProtectionQuoteRequestShipmentInfoShipperInfoAddress from './ParcelProtectionQuoteRequestShipmentInfoShipperInfoAddress';

/**
 * The ParcelProtectionQuoteRequestShipmentInfoConsigneeInfo model module.
 * @module PB.ShippingAPI/model/ParcelProtectionQuoteRequestShipmentInfoConsigneeInfo
 * @version 1.0.0
 */
class ParcelProtectionQuoteRequestShipmentInfoConsigneeInfo {
    /**
     * Constructs a new <code>ParcelProtectionQuoteRequestShipmentInfoConsigneeInfo</code>.
     * @alias module:PB.ShippingAPI/model/ParcelProtectionQuoteRequestShipmentInfoConsigneeInfo
     * @param address {module:PB.ShippingAPI/model/ParcelProtectionQuoteRequestShipmentInfoShipperInfoAddress} 
     */
    constructor(address) { 
        
        ParcelProtectionQuoteRequestShipmentInfoConsigneeInfo.initialize(this, address);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, address) { 
        obj['address'] = address;
    }

    /**
     * Constructs a <code>ParcelProtectionQuoteRequestShipmentInfoConsigneeInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PB.ShippingAPI/model/ParcelProtectionQuoteRequestShipmentInfoConsigneeInfo} obj Optional instance to populate.
     * @return {module:PB.ShippingAPI/model/ParcelProtectionQuoteRequestShipmentInfoConsigneeInfo} The populated <code>ParcelProtectionQuoteRequestShipmentInfoConsigneeInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ParcelProtectionQuoteRequestShipmentInfoConsigneeInfo();

            if (data.hasOwnProperty('address')) {
                obj['address'] = ParcelProtectionQuoteRequestShipmentInfoShipperInfoAddress.constructFromObject(data['address']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:PB.ShippingAPI/model/ParcelProtectionQuoteRequestShipmentInfoShipperInfoAddress} address
 */
ParcelProtectionQuoteRequestShipmentInfoConsigneeInfo.prototype['address'] = undefined;






export default ParcelProtectionQuoteRequestShipmentInfoConsigneeInfo;

