/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ParcelProtectionQuoteResponseParcelProtectionFeesBreakup model module.
 * @module PB.ShippingAPI/model/ParcelProtectionQuoteResponseParcelProtectionFeesBreakup
 * @version 1.0.0
 */
class ParcelProtectionQuoteResponseParcelProtectionFeesBreakup {
    /**
     * Constructs a new <code>ParcelProtectionQuoteResponseParcelProtectionFeesBreakup</code>.
     * @alias module:PB.ShippingAPI/model/ParcelProtectionQuoteResponseParcelProtectionFeesBreakup
     * @param basePremium {Number} 
     * @param technologyFee {Number} 
     */
    constructor(basePremium, technologyFee) { 
        
        ParcelProtectionQuoteResponseParcelProtectionFeesBreakup.initialize(this, basePremium, technologyFee);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, basePremium, technologyFee) { 
        obj['basePremium'] = basePremium;
        obj['technologyFee'] = technologyFee;
    }

    /**
     * Constructs a <code>ParcelProtectionQuoteResponseParcelProtectionFeesBreakup</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PB.ShippingAPI/model/ParcelProtectionQuoteResponseParcelProtectionFeesBreakup} obj Optional instance to populate.
     * @return {module:PB.ShippingAPI/model/ParcelProtectionQuoteResponseParcelProtectionFeesBreakup} The populated <code>ParcelProtectionQuoteResponseParcelProtectionFeesBreakup</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ParcelProtectionQuoteResponseParcelProtectionFeesBreakup();

            if (data.hasOwnProperty('basePremium')) {
                obj['basePremium'] = ApiClient.convertToType(data['basePremium'], 'Number');
            }
            if (data.hasOwnProperty('technologyFee')) {
                obj['technologyFee'] = ApiClient.convertToType(data['technologyFee'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} basePremium
 */
ParcelProtectionQuoteResponseParcelProtectionFeesBreakup.prototype['basePremium'] = undefined;

/**
 * @member {Number} technologyFee
 */
ParcelProtectionQuoteResponseParcelProtectionFeesBreakup.prototype['technologyFee'] = undefined;






export default ParcelProtectionQuoteResponseParcelProtectionFeesBreakup;

