/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ParcelProtectionQuoteRequestShipmentInfo from './ParcelProtectionQuoteRequestShipmentInfo';

/**
 * The ParcelProtectionQuoteRequest model module.
 * @module PB.ShippingAPI/model/ParcelProtectionQuoteRequest
 * @version 1.0.0
 */
class ParcelProtectionQuoteRequest {
    /**
     * Constructs a new <code>ParcelProtectionQuoteRequest</code>.
     * @alias module:PB.ShippingAPI/model/ParcelProtectionQuoteRequest
     * @param shipmentInfo {module:PB.ShippingAPI/model/ParcelProtectionQuoteRequestShipmentInfo} 
     */
    constructor(shipmentInfo) { 
        
        ParcelProtectionQuoteRequest.initialize(this, shipmentInfo);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, shipmentInfo) { 
        obj['shipmentInfo'] = shipmentInfo;
    }

    /**
     * Constructs a <code>ParcelProtectionQuoteRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PB.ShippingAPI/model/ParcelProtectionQuoteRequest} obj Optional instance to populate.
     * @return {module:PB.ShippingAPI/model/ParcelProtectionQuoteRequest} The populated <code>ParcelProtectionQuoteRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ParcelProtectionQuoteRequest();

            if (data.hasOwnProperty('parcelProtectionAccountID')) {
                obj['parcelProtectionAccountID'] = ApiClient.convertToType(data['parcelProtectionAccountID'], 'String');
            }
            if (data.hasOwnProperty('parcelProtectionProgramID')) {
                obj['parcelProtectionProgramID'] = ApiClient.convertToType(data['parcelProtectionProgramID'], 'String');
            }
            if (data.hasOwnProperty('shipmentInfo')) {
                obj['shipmentInfo'] = ParcelProtectionQuoteRequestShipmentInfo.constructFromObject(data['shipmentInfo']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} parcelProtectionAccountID
 */
ParcelProtectionQuoteRequest.prototype['parcelProtectionAccountID'] = undefined;

/**
 * @member {String} parcelProtectionProgramID
 */
ParcelProtectionQuoteRequest.prototype['parcelProtectionProgramID'] = undefined;

/**
 * @member {module:PB.ShippingAPI/model/ParcelProtectionQuoteRequestShipmentInfo} shipmentInfo
 */
ParcelProtectionQuoteRequest.prototype['shipmentInfo'] = undefined;






export default ParcelProtectionQuoteRequest;

