/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ParcelDimension from './ParcelDimension';
import ParcelWeight from './ParcelWeight';

/**
 * The Parcel model module.
 * @module PB.ShippingAPI/model/Parcel
 * @version 1.0.0
 */
class Parcel {
    /**
     * Constructs a new <code>Parcel</code>.
     * @alias module:PB.ShippingAPI/model/Parcel
     */
    constructor() { 
        
        Parcel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Parcel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PB.ShippingAPI/model/Parcel} obj Optional instance to populate.
     * @return {module:PB.ShippingAPI/model/Parcel} The populated <code>Parcel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Parcel();

            if (data.hasOwnProperty('dimension')) {
                obj['dimension'] = ParcelDimension.constructFromObject(data['dimension']);
            }
            if (data.hasOwnProperty('weight')) {
                obj['weight'] = ParcelWeight.constructFromObject(data['weight']);
            }
            if (data.hasOwnProperty('valueOfGoods')) {
                obj['valueOfGoods'] = ApiClient.convertToType(data['valueOfGoods'], 'Number');
            }
            if (data.hasOwnProperty('currencyCode')) {
                obj['currencyCode'] = ApiClient.convertToType(data['currencyCode'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:PB.ShippingAPI/model/ParcelDimension} dimension
 */
Parcel.prototype['dimension'] = undefined;

/**
 * @member {module:PB.ShippingAPI/model/ParcelWeight} weight
 */
Parcel.prototype['weight'] = undefined;

/**
 * @member {Number} valueOfGoods
 */
Parcel.prototype['valueOfGoods'] = undefined;

/**
 * Currency code as per [IOS 4217](https://en.wikipedia.org/wiki/ISO_4217)
 * @member {String} currencyCode
 */
Parcel.prototype['currencyCode'] = undefined;






export default Parcel;

