/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SpecialServiceCodes from './SpecialServiceCodes';

/**
 * The PrerequisiteRules model module.
 * @module PB.ShippingAPI/model/PrerequisiteRules
 * @version 1.0.0
 */
class PrerequisiteRules {
    /**
     * Constructs a new <code>PrerequisiteRules</code>.
     * @alias module:PB.ShippingAPI/model/PrerequisiteRules
     */
    constructor() { 
        
        PrerequisiteRules.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PrerequisiteRules</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PB.ShippingAPI/model/PrerequisiteRules} obj Optional instance to populate.
     * @return {module:PB.ShippingAPI/model/PrerequisiteRules} The populated <code>PrerequisiteRules</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PrerequisiteRules();

            if (data.hasOwnProperty('specialServiceCodes')) {
                obj['specialServiceCodes'] = SpecialServiceCodes.constructFromObject(data['specialServiceCodes']);
            }
            if (data.hasOwnProperty('minInputValue')) {
                obj['minInputValue'] = ApiClient.convertToType(data['minInputValue'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {module:PB.ShippingAPI/model/SpecialServiceCodes} specialServiceCodes
 */
PrerequisiteRules.prototype['specialServiceCodes'] = undefined;

/**
 * @member {Number} minInputValue
 */
PrerequisiteRules.prototype['minInputValue'] = undefined;






export default PrerequisiteRules;

