/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SchedulePickupTotalWeight from './SchedulePickupTotalWeight';

/**
 * The SchedulePickupPickupSummary model module.
 * @module PB.ShippingAPI/model/SchedulePickupPickupSummary
 * @version 1.0.0
 */
class SchedulePickupPickupSummary {
    /**
     * Constructs a new <code>SchedulePickupPickupSummary</code>.
     * @alias module:PB.ShippingAPI/model/SchedulePickupPickupSummary
     */
    constructor() { 
        
        SchedulePickupPickupSummary.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SchedulePickupPickupSummary</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PB.ShippingAPI/model/SchedulePickupPickupSummary} obj Optional instance to populate.
     * @return {module:PB.ShippingAPI/model/SchedulePickupPickupSummary} The populated <code>SchedulePickupPickupSummary</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SchedulePickupPickupSummary();

            if (data.hasOwnProperty('serviceId')) {
                obj['serviceId'] = ApiClient.convertToType(data['serviceId'], 'String');
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
            if (data.hasOwnProperty('totalWeight')) {
                obj['totalWeight'] = SchedulePickupTotalWeight.constructFromObject(data['totalWeight']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} serviceId
 */
SchedulePickupPickupSummary.prototype['serviceId'] = undefined;

/**
 * @member {Number} count
 */
SchedulePickupPickupSummary.prototype['count'] = undefined;

/**
 * @member {module:PB.ShippingAPI/model/SchedulePickupTotalWeight} totalWeight
 */
SchedulePickupPickupSummary.prototype['totalWeight'] = undefined;






export default SchedulePickupPickupSummary;

