/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TrackingResponseScanDetailsList model module.
 * @module PB.ShippingAPI/model/TrackingResponseScanDetailsList
 * @version 1.0.0
 */
class TrackingResponseScanDetailsList {
    /**
     * Constructs a new <code>TrackingResponseScanDetailsList</code>.
     * @alias module:PB.ShippingAPI/model/TrackingResponseScanDetailsList
     */
    constructor() { 
        
        TrackingResponseScanDetailsList.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TrackingResponseScanDetailsList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PB.ShippingAPI/model/TrackingResponseScanDetailsList} obj Optional instance to populate.
     * @return {module:PB.ShippingAPI/model/TrackingResponseScanDetailsList} The populated <code>TrackingResponseScanDetailsList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TrackingResponseScanDetailsList();

            if (data.hasOwnProperty('eventDate')) {
                obj['eventDate'] = ApiClient.convertToType(data['eventDate'], 'Date');
            }
            if (data.hasOwnProperty('eventTime')) {
                obj['eventTime'] = ApiClient.convertToType(data['eventTime'], 'String');
            }
            if (data.hasOwnProperty('eventCity')) {
                obj['eventCity'] = ApiClient.convertToType(data['eventCity'], 'String');
            }
            if (data.hasOwnProperty('eventStateOrProvince')) {
                obj['eventStateOrProvince'] = ApiClient.convertToType(data['eventStateOrProvince'], 'String');
            }
            if (data.hasOwnProperty('postalCode')) {
                obj['postalCode'] = ApiClient.convertToType(data['postalCode'], 'Number');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
            if (data.hasOwnProperty('scanType')) {
                obj['scanType'] = ApiClient.convertToType(data['scanType'], 'String');
            }
            if (data.hasOwnProperty('scanDescription')) {
                obj['scanDescription'] = ApiClient.convertToType(data['scanDescription'], 'String');
            }
            if (data.hasOwnProperty('packageStatus')) {
                obj['packageStatus'] = ApiClient.convertToType(data['packageStatus'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Date} eventDate
 */
TrackingResponseScanDetailsList.prototype['eventDate'] = undefined;

/**
 * @member {String} eventTime
 */
TrackingResponseScanDetailsList.prototype['eventTime'] = undefined;

/**
 * @member {String} eventCity
 */
TrackingResponseScanDetailsList.prototype['eventCity'] = undefined;

/**
 * @member {String} eventStateOrProvince
 */
TrackingResponseScanDetailsList.prototype['eventStateOrProvince'] = undefined;

/**
 * @member {Number} postalCode
 */
TrackingResponseScanDetailsList.prototype['postalCode'] = undefined;

/**
 * @member {String} country
 */
TrackingResponseScanDetailsList.prototype['country'] = undefined;

/**
 * @member {String} scanType
 */
TrackingResponseScanDetailsList.prototype['scanType'] = undefined;

/**
 * @member {String} scanDescription
 */
TrackingResponseScanDetailsList.prototype['scanDescription'] = undefined;

/**
 * @member {String} packageStatus
 */
TrackingResponseScanDetailsList.prototype['packageStatus'] = undefined;






export default TrackingResponseScanDetailsList;

