/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VoidParcelProtectionRequest model module.
 * @module PB.ShippingAPI/model/VoidParcelProtectionRequest
 * @version 1.0.0
 */
class VoidParcelProtectionRequest {
    /**
     * Constructs a new <code>VoidParcelProtectionRequest</code>.
     * @alias module:PB.ShippingAPI/model/VoidParcelProtectionRequest
     */
    constructor() { 
        
        VoidParcelProtectionRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VoidParcelProtectionRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PB.ShippingAPI/model/VoidParcelProtectionRequest} obj Optional instance to populate.
     * @return {module:PB.ShippingAPI/model/VoidParcelProtectionRequest} The populated <code>VoidParcelProtectionRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VoidParcelProtectionRequest();

            if (data.hasOwnProperty('shipperID')) {
                obj['shipperID'] = ApiClient.convertToType(data['shipperID'], 'String');
            }
            if (data.hasOwnProperty('parcelProtectionAccountID')) {
                obj['parcelProtectionAccountID'] = ApiClient.convertToType(data['parcelProtectionAccountID'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} shipperID
 */
VoidParcelProtectionRequest.prototype['shipperID'] = undefined;

/**
 * Parcel Protection account ID, if applicable.
 * @member {String} parcelProtectionAccountID
 */
VoidParcelProtectionRequest.prototype['parcelProtectionAccountID'] = undefined;






export default VoidParcelProtectionRequest;

