/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The WeightRules model module.
 * @module PB.ShippingAPI/model/WeightRules
 * @version 1.0.0
 */
class WeightRules {
    /**
     * Constructs a new <code>WeightRules</code>.
     * @alias module:PB.ShippingAPI/model/WeightRules
     */
    constructor() { 
        
        WeightRules.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WeightRules</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:PB.ShippingAPI/model/WeightRules} obj Optional instance to populate.
     * @return {module:PB.ShippingAPI/model/WeightRules} The populated <code>WeightRules</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WeightRules();

            if (data.hasOwnProperty('required')) {
                obj['required'] = ApiClient.convertToType(data['required'], 'Boolean');
            }
            if (data.hasOwnProperty('unitOfMeasurement')) {
                obj['unitOfMeasurement'] = ApiClient.convertToType(data['unitOfMeasurement'], 'String');
            }
            if (data.hasOwnProperty('minWeight')) {
                obj['minWeight'] = ApiClient.convertToType(data['minWeight'], 'Number');
            }
            if (data.hasOwnProperty('maxWeight')) {
                obj['maxWeight'] = ApiClient.convertToType(data['maxWeight'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} required
 */
WeightRules.prototype['required'] = undefined;

/**
 * @member {String} unitOfMeasurement
 */
WeightRules.prototype['unitOfMeasurement'] = undefined;

/**
 * @member {Number} minWeight
 */
WeightRules.prototype['minWeight'] = undefined;

/**
 * @member {Number} maxWeight
 */
WeightRules.prototype['maxWeight'] = undefined;






export default WeightRules;

