/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/PB.ShippingAPI/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/PB.ShippingAPI/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ShippingApi);
  }
}(this, function(expect, ShippingApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ShippingApi.AddTrackingEventsEvents();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AddTrackingEventsEvents', function() {
    it('should create an instance of AddTrackingEventsEvents', function() {
      // uncomment below and update the code to test AddTrackingEventsEvents
      //var instane = new ShippingApi.AddTrackingEventsEvents();
      //expect(instance).to.be.a(ShippingApi.AddTrackingEventsEvents);
    });

    it('should have the property eventCode (base name: "eventCode")', function() {
      // uncomment below and update the code to test the property eventCode
      //var instane = new ShippingApi.AddTrackingEventsEvents();
      //expect(instance).to.be();
    });

    it('should have the property carrierEventCode (base name: "carrierEventCode")', function() {
      // uncomment below and update the code to test the property carrierEventCode
      //var instane = new ShippingApi.AddTrackingEventsEvents();
      //expect(instance).to.be();
    });

    it('should have the property eventDate (base name: "eventDate")', function() {
      // uncomment below and update the code to test the property eventDate
      //var instane = new ShippingApi.AddTrackingEventsEvents();
      //expect(instance).to.be();
    });

    it('should have the property eventTime (base name: "eventTime")', function() {
      // uncomment below and update the code to test the property eventTime
      //var instane = new ShippingApi.AddTrackingEventsEvents();
      //expect(instance).to.be();
    });

    it('should have the property eventTimeOffset (base name: "eventTimeOffset")', function() {
      // uncomment below and update the code to test the property eventTimeOffset
      //var instane = new ShippingApi.AddTrackingEventsEvents();
      //expect(instance).to.be();
    });

    it('should have the property eventCity (base name: "eventCity")', function() {
      // uncomment below and update the code to test the property eventCity
      //var instane = new ShippingApi.AddTrackingEventsEvents();
      //expect(instance).to.be();
    });

    it('should have the property eventStateOrProvince (base name: "eventStateOrProvince")', function() {
      // uncomment below and update the code to test the property eventStateOrProvince
      //var instane = new ShippingApi.AddTrackingEventsEvents();
      //expect(instance).to.be();
    });

    it('should have the property postalCode (base name: "postalCode")', function() {
      // uncomment below and update the code to test the property postalCode
      //var instane = new ShippingApi.AddTrackingEventsEvents();
      //expect(instance).to.be();
    });

    it('should have the property country (base name: "country")', function() {
      // uncomment below and update the code to test the property country
      //var instane = new ShippingApi.AddTrackingEventsEvents();
      //expect(instance).to.be();
    });

  });

}));
