/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/PB.ShippingAPI/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/PB.ShippingAPI/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ShippingApi);
  }
}(this, function(expect, ShippingApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ShippingApi.CrossBorderQuotesErrorsQuoteLines();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CrossBorderQuotesErrorsQuoteLines', function() {
    it('should create an instance of CrossBorderQuotesErrorsQuoteLines', function() {
      // uncomment below and update the code to test CrossBorderQuotesErrorsQuoteLines
      //var instane = new ShippingApi.CrossBorderQuotesErrorsQuoteLines();
      //expect(instance).to.be.a(ShippingApi.CrossBorderQuotesErrorsQuoteLines);
    });

    it('should have the property lineId (base name: "lineId")', function() {
      // uncomment below and update the code to test the property lineId
      //var instane = new ShippingApi.CrossBorderQuotesErrorsQuoteLines();
      //expect(instance).to.be();
    });

    it('should have the property merchantComRefId (base name: "merchantComRefId")', function() {
      // uncomment below and update the code to test the property merchantComRefId
      //var instane = new ShippingApi.CrossBorderQuotesErrorsQuoteLines();
      //expect(instance).to.be();
    });

    it('should have the property quantity (base name: "quantity")', function() {
      // uncomment below and update the code to test the property quantity
      //var instane = new ShippingApi.CrossBorderQuotesErrorsQuoteLines();
      //expect(instance).to.be();
    });

    it('should have the property unitErrors (base name: "unitErrors")', function() {
      // uncomment below and update the code to test the property unitErrors
      //var instane = new ShippingApi.CrossBorderQuotesErrorsQuoteLines();
      //expect(instance).to.be();
    });

  });

}));
