/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/PB.ShippingAPI/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/PB.ShippingAPI/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ShippingApi);
  }
}(this, function(expect, ShippingApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ShippingApi.CrossBorderQuotesRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CrossBorderQuotesRequest', function() {
    it('should create an instance of CrossBorderQuotesRequest', function() {
      // uncomment below and update the code to test CrossBorderQuotesRequest
      //var instane = new ShippingApi.CrossBorderQuotesRequest();
      //expect(instance).to.be.a(ShippingApi.CrossBorderQuotesRequest);
    });

    it('should have the property quoteCurrency (base name: "quoteCurrency")', function() {
      // uncomment below and update the code to test the property quoteCurrency
      //var instane = new ShippingApi.CrossBorderQuotesRequest();
      //expect(instance).to.be();
    });

    it('should have the property basketCurrency (base name: "basketCurrency")', function() {
      // uncomment below and update the code to test the property basketCurrency
      //var instane = new ShippingApi.CrossBorderQuotesRequest();
      //expect(instance).to.be();
    });

    it('should have the property fromAddress (base name: "fromAddress")', function() {
      // uncomment below and update the code to test the property fromAddress
      //var instane = new ShippingApi.CrossBorderQuotesRequest();
      //expect(instance).to.be();
    });

    it('should have the property toAddress (base name: "toAddress")', function() {
      // uncomment below and update the code to test the property toAddress
      //var instane = new ShippingApi.CrossBorderQuotesRequest();
      //expect(instance).to.be();
    });

    it('should have the property basketItems (base name: "basketItems")', function() {
      // uncomment below and update the code to test the property basketItems
      //var instane = new ShippingApi.CrossBorderQuotesRequest();
      //expect(instance).to.be();
    });

    it('should have the property rates (base name: "rates")', function() {
      // uncomment below and update the code to test the property rates
      //var instane = new ShippingApi.CrossBorderQuotesRequest();
      //expect(instance).to.be();
    });

    it('should have the property shipmentOptions (base name: "shipmentOptions")', function() {
      // uncomment below and update the code to test the property shipmentOptions
      //var instane = new ShippingApi.CrossBorderQuotesRequest();
      //expect(instance).to.be();
    });

  });

}));
