/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/PB.ShippingAPI/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/PB.ShippingAPI/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ShippingApi);
  }
}(this, function(expect, ShippingApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ShippingApi.ParcelTypeRules();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ParcelTypeRules', function() {
    it('should create an instance of ParcelTypeRules', function() {
      // uncomment below and update the code to test ParcelTypeRules
      //var instane = new ShippingApi.ParcelTypeRules();
      //expect(instance).to.be.a(ShippingApi.ParcelTypeRules);
    });

    it('should have the property parcelType (base name: "parcelType")', function() {
      // uncomment below and update the code to test the property parcelType
      //var instane = new ShippingApi.ParcelTypeRules();
      //expect(instance).to.be();
    });

    it('should have the property brandedName (base name: "brandedName")', function() {
      // uncomment below and update the code to test the property brandedName
      //var instane = new ShippingApi.ParcelTypeRules();
      //expect(instance).to.be();
    });

    it('should have the property rateTypeId (base name: "rateTypeId")', function() {
      // uncomment below and update the code to test the property rateTypeId
      //var instane = new ShippingApi.ParcelTypeRules();
      //expect(instance).to.be();
    });

    it('should have the property rateTypeBrandedName (base name: "rateTypeBrandedName")', function() {
      // uncomment below and update the code to test the property rateTypeBrandedName
      //var instane = new ShippingApi.ParcelTypeRules();
      //expect(instance).to.be();
    });

    it('should have the property trackable (base name: "trackable")', function() {
      // uncomment below and update the code to test the property trackable
      //var instane = new ShippingApi.ParcelTypeRules();
      //expect(instance).to.be();
    });

    it('should have the property specialServicesRule (base name: "specialServicesRule")', function() {
      // uncomment below and update the code to test the property specialServicesRule
      //var instane = new ShippingApi.ParcelTypeRules();
      //expect(instance).to.be();
    });

    it('should have the property weightRules (base name: "weightRules")', function() {
      // uncomment below and update the code to test the property weightRules
      //var instane = new ShippingApi.ParcelTypeRules();
      //expect(instance).to.be();
    });

    it('should have the property dimensionRules (base name: "dimensionRules")', function() {
      // uncomment below and update the code to test the property dimensionRules
      //var instane = new ShippingApi.ParcelTypeRules();
      //expect(instance).to.be();
    });

    it('should have the property suggestedTrackableSpecialServiceId (base name: "suggestedTrackableSpecialServiceId")', function() {
      // uncomment below and update the code to test the property suggestedTrackableSpecialServiceId
      //var instane = new ShippingApi.ParcelTypeRules();
      //expect(instance).to.be();
    });

  });

}));
