/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/PB.ShippingAPI/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/PB.ShippingAPI/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ShippingApi);
  }
}(this, function(expect, ShippingApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ShippingApi.ParcelProtectionPolicyResponseContent();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ParcelProtectionPolicyResponseContent', function() {
    it('should create an instance of ParcelProtectionPolicyResponseContent', function() {
      // uncomment below and update the code to test ParcelProtectionPolicyResponseContent
      //var instane = new ShippingApi.ParcelProtectionPolicyResponseContent();
      //expect(instance).to.be.a(ShippingApi.ParcelProtectionPolicyResponseContent);
    });

    it('should have the property transactionId (base name: "transactionId")', function() {
      // uncomment below and update the code to test the property transactionId
      //var instane = new ShippingApi.ParcelProtectionPolicyResponseContent();
      //expect(instance).to.be();
    });

    it('should have the property developerId (base name: "developerId")', function() {
      // uncomment below and update the code to test the property developerId
      //var instane = new ShippingApi.ParcelProtectionPolicyResponseContent();
      //expect(instance).to.be();
    });

    it('should have the property subscriptionAccNo (base name: "subscriptionAccNo")', function() {
      // uncomment below and update the code to test the property subscriptionAccNo
      //var instane = new ShippingApi.ParcelProtectionPolicyResponseContent();
      //expect(instance).to.be();
    });

    it('should have the property clientTransactionId (base name: "clientTransactionId")', function() {
      // uncomment below and update the code to test the property clientTransactionId
      //var instane = new ShippingApi.ParcelProtectionPolicyResponseContent();
      //expect(instance).to.be();
    });

    it('should have the property policyDetails (base name: "policyDetails")', function() {
      // uncomment below and update the code to test the property policyDetails
      //var instane = new ShippingApi.ParcelProtectionPolicyResponseContent();
      //expect(instance).to.be();
    });

    it('should have the property shipmentDetails (base name: "shipmentDetails")', function() {
      // uncomment below and update the code to test the property shipmentDetails
      //var instane = new ShippingApi.ParcelProtectionPolicyResponseContent();
      //expect(instance).to.be();
    });

    it('should have the property shipperInfo (base name: "shipperInfo")', function() {
      // uncomment below and update the code to test the property shipperInfo
      //var instane = new ShippingApi.ParcelProtectionPolicyResponseContent();
      //expect(instance).to.be();
    });

    it('should have the property consigneeInfo (base name: "consigneeInfo")', function() {
      // uncomment below and update the code to test the property consigneeInfo
      //var instane = new ShippingApi.ParcelProtectionPolicyResponseContent();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instane = new ShippingApi.ParcelProtectionPolicyResponseContent();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updatedAt")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instane = new ShippingApi.ParcelProtectionPolicyResponseContent();
      //expect(instance).to.be();
    });

  });

}));
