/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/PB.ShippingAPI/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/PB.ShippingAPI/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ShippingApi);
  }
}(this, function(expect, ShippingApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ShippingApi.SchedulePickup();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SchedulePickup', function() {
    it('should create an instance of SchedulePickup', function() {
      // uncomment below and update the code to test SchedulePickup
      //var instane = new ShippingApi.SchedulePickup();
      //expect(instance).to.be.a(ShippingApi.SchedulePickup);
    });

    it('should have the property pickupAddress (base name: "pickupAddress")', function() {
      // uncomment below and update the code to test the property pickupAddress
      //var instane = new ShippingApi.SchedulePickup();
      //expect(instance).to.be();
    });

    it('should have the property carrier (base name: "carrier")', function() {
      // uncomment below and update the code to test the property carrier
      //var instane = new ShippingApi.SchedulePickup();
      //expect(instance).to.be();
    });

    it('should have the property pickupSummary (base name: "pickupSummary")', function() {
      // uncomment below and update the code to test the property pickupSummary
      //var instane = new ShippingApi.SchedulePickup();
      //expect(instance).to.be();
    });

    it('should have the property reference (base name: "reference")', function() {
      // uncomment below and update the code to test the property reference
      //var instane = new ShippingApi.SchedulePickup();
      //expect(instance).to.be();
    });

    it('should have the property packageLocation (base name: "packageLocation")', function() {
      // uncomment below and update the code to test the property packageLocation
      //var instane = new ShippingApi.SchedulePickup();
      //expect(instance).to.be();
    });

    it('should have the property specialInstructions (base name: "specialInstructions")', function() {
      // uncomment below and update the code to test the property specialInstructions
      //var instane = new ShippingApi.SchedulePickup();
      //expect(instance).to.be();
    });

  });

}));
