/**
 * Shipping API
 * Shipping API Sample.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@pb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Errors from '../model/Errors';
import PageRealTransactionDetailReport from '../model/PageRealTransactionDetailReport';

/**
* TransactionReports service.
* @module PB.ShippingAPI/api/TransactionReportsApi
* @version 1.0.0
*/
export default class TransactionReportsApi {

    /**
    * Constructs a new TransactionReportsApi. 
    * @alias module:PB.ShippingAPI/api/TransactionReportsApi
    * @class
    * @param {module:PB.ShippingAPI/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:PB.ShippingAPI/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getTransactionReport operation.
     * @callback module:PB.ShippingAPI/api/TransactionReportsApi~getTransactionReportCallback
     * @param {String} error Error message, if any.
     * @param {module:PB.ShippingAPI/model/PageRealTransactionDetailReport} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * This operation retrieves all transactions for a specified period of time.
     * @param {String} developerId developerId
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.xPBUnifiedErrorStructure Set this to true to use the standard [error object](https://shipping.pitneybowes.com/reference/error-object.html#standard-error-object) if an error occurs. (default to true)
     * @param {Date} opts.fromDate fromDate
     * @param {module:PB.ShippingAPI/model/Number} opts.shipDetails  (default to 0)
     * @param {Number} opts.page 
     * @param {Number} opts.size  (default to 20)
     * @param {module:PB.ShippingAPI/model/String} opts.printStatus printStatus
     * @param {Date} opts.toDate toDate
     * @param {module:PB.ShippingAPI/model/String} opts.transactionType transactionType
     * @param {String} opts.merchantId The value of the postalReportingNumber element in the [merchant object](https://shipping.pitneybowes.com/reference/resource-objects.html). This value is also the merchant's Shipper ID.
     * @param {String} opts.sort Defines a property to sort on and the sort order. Sort order can be ascending (asc) or descending (desc). Use the following form-  * **sort=<property_name>,<sort_direction>** For example- **sort=transactionId,desc** 
     * @param {String} opts.parcelTrackingNumber Parcel tracking number of the shipment.
     * @param {String} opts.transactionId The unique string that identifies all the transactions associated with a given shipment. The string comprises the developer ID and the shipment's X-PB-TransactionId, separated by an underscore (_). For example-  * **transactionId=44397664_ad5aa07-ad7414-a78a-c22b3**
     * @param {module:PB.ShippingAPI/api/TransactionReportsApi~getTransactionReportCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:PB.ShippingAPI/model/PageRealTransactionDetailReport}
     */
    getTransactionReport(developerId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'developerId' is set
      if (developerId === undefined || developerId === null) {
        throw new Error("Missing the required parameter 'developerId' when calling getTransactionReport");
      }

      let pathParams = {
        'developerId': developerId
      };
      let queryParams = {
        'fromDate': opts['fromDate'],
        'shipDetails': opts['shipDetails'],
        'page': opts['page'],
        'size': opts['size'],
        'printStatus': opts['printStatus'],
        'toDate': opts['toDate'],
        'transactionType': opts['transactionType'],
        'merchantId': opts['merchantId'],
        'sort': opts['sort'],
        'parcelTrackingNumber': opts['parcelTrackingNumber']
      };
      let headerParams = {
        'X-PB-UnifiedErrorStructure': opts['xPBUnifiedErrorStructure'],
        'transactionId': opts['transactionId']
      };
      let formParams = {
      };

      let authNames = ['oAuth2ClientCredentials'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PageRealTransactionDetailReport;
      return this.apiClient.callApi(
        '/v4/ledger/developers/{developerId}/transactions/reports', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
